package com.uxicons.compose.uicons.solid.rounded

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import com.uxicons.compose.uicons.Icons
import com.uxicons.compose.uicons.core.UXIcon

private var _TruckLadder: ImageVector? = null

val Icons.Sr.TruckLadder: ImageVector
    get() = _TruckLadder ?: UXIcon(name = "TruckLadder") {
            path(fill = SolidColor(Color.Black)) {
                moveTo(14f, 1f)
                horizontalLineToRelative(0f)
                curveToRelative(0f, -0.55f, -0.45f, -1f, -1f, -1f)
                lineTo(1f, 0f)
                curveTo(0.45f, 0f, 0f, 0.45f, 0f, 1f)
                lineTo(0f, 1f)
                curveTo(0f, 1.55f, 0.45f, 2f, 1f, 2f)
                horizontalLineToRelative(1f)
                lineTo(2f, 6f)
                lineTo(1f, 6f)
                curveTo(0.45f, 6f, 0f, 6.45f, 0f, 7f)
                lineTo(0f, 7f)
                curveTo(0f, 7.55f, 0.45f, 8f, 1f, 8f)
                lineTo(13f, 8f)
                curveToRelative(0.55f, 0f, 1f, -0.45f, 1f, -1f)
                horizontalLineToRelative(0f)
                curveToRelative(0f, -0.55f, -0.45f, -1f, -1f, -1f)
                horizontalLineToRelative(-1f)
                lineTo(12f, 2f)
                horizontalLineToRelative(1f)
                curveToRelative(0.55f, 0f, 1f, -0.45f, 1f, -1f)
                close()
                moveTo(6f, 6f)
                horizontalLineToRelative(-2f)
                lineTo(4f, 2f)
                horizontalLineToRelative(2f)
                lineTo(6f, 6f)
                close()
                moveTo(10f, 6f)
                horizontalLineToRelative(-2f)
                lineTo(8f, 2f)
                horizontalLineToRelative(2f)
                lineTo(10f, 6f)
                close()
                moveTo(11.94f, 20f)
                curveToRelative(0.03f, 0.16f, 0.06f, 0.33f, 0.06f, 0.5f)
                curveToRelative(0f, 1.38f, -1.12f, 2.5f, -2.5f, 2.5f)
                reflectiveCurveToRelative(-2.5f, -1.12f, -2.5f, -2.5f)
                curveToRelative(0f, -0.17f, 0.02f, -0.34f, 0.06f, -0.5f)
                horizontalLineToRelative(4.88f)
                close()
                moveTo(4.94f, 20f)
                curveToRelative(0.03f, 0.16f, 0.06f, 0.33f, 0.06f, 0.5f)
                curveToRelative(0f, 1.38f, -1.12f, 2.5f, -2.5f, 2.5f)
                reflectiveCurveToRelative(-2.5f, -1.12f, -2.5f, -2.5f)
                curveToRelative(0f, -0.17f, 0.02f, -0.34f, 0.06f, -0.5f)
                lineTo(4.94f, 20f)
                close()
                moveTo(3.5f, 10f)
                lineTo(14f, 10f)
                verticalLineToRelative(8f)
                lineTo(0f, 18f)
                verticalLineToRelative(-4.5f)
                curveToRelative(0f, -1.93f, 1.57f, -3.5f, 3.5f, -3.5f)
                close()
                moveTo(21.94f, 20f)
                curveToRelative(0.03f, 0.16f, 0.06f, 0.33f, 0.06f, 0.5f)
                curveToRelative(0f, 1.38f, -1.12f, 2.5f, -2.5f, 2.5f)
                reflectiveCurveToRelative(-2.5f, -1.12f, -2.5f, -2.5f)
                curveToRelative(0f, -0.17f, 0.02f, -0.34f, 0.06f, -0.5f)
                horizontalLineToRelative(4.88f)
                close()
                moveTo(23.72f, 11f)
                horizontalLineToRelative(-7.72f)
                lineTo(16.0f, 7f)
                curveToRelative(0f, -1.1f, 0.9f, -2f, 2f, -2f)
                horizontalLineToRelative(0.84f)
                curveToRelative(1.72f, 0f, 3.25f, 1.1f, 3.79f, 2.73f)
                lineToRelative(1.09f, 3.27f)
                moveToRelative(-3.72f, 7f)
                horizontalLineToRelative(-4f)
                verticalLineToRelative(-5f)
                horizontalLineToRelative(8f)
                verticalLineToRelative(1f)
                curveToRelative(0f, 2.21f, -1.79f, 4f, -4f, 4f)
                close()
            }
        }.also { _TruckLadder = it}
