package com.uxicons.compose.uicons.solid.straight

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import com.uxicons.compose.uicons.Icons
import com.uxicons.compose.uicons.core.UXIcon

private var _HandsTypingKeyboard: ImageVector? = null

val Icons.Ss.HandsTypingKeyboard: ImageVector
    get() = _HandsTypingKeyboard ?: UXIcon(name = "HandsTypingKeyboard") {
            path(fill = SolidColor(Color.Black)) {
                moveToRelative(10f, 14f)
                verticalLineToRelative(-1.5f)
                curveToRelative(0f, -0.98f, -0.41f, -1.86f, -1.06f, -2.5f)
                horizontalLineToRelative(6.12f)
                curveToRelative(-0.65f, 0.64f, -1.06f, 1.52f, -1.06f, 2.5f)
                verticalLineToRelative(1.5f)
                horizontalLineToRelative(-4f)
                close()
                moveTo(11.18f, 18.34f)
                curveToRelative(-0.79f, -0.57f, -1.88f, -0.39f, -2.56f, 0.28f)
                lineToRelative(-0.62f, 0.63f)
                verticalLineToRelative(-6.75f)
                curveToRelative(0f, -0.83f, -0.67f, -1.5f, -1.5f, -1.5f)
                reflectiveCurveToRelative(-1.5f, 0.67f, -1.5f, 1.5f)
                verticalLineToRelative(3.32f)
                lineToRelative(-5f, 2.0f)
                verticalLineToRelative(6.18f)
                horizontalLineToRelative(8.62f)
                lineToRelative(2.81f, -2.71f)
                curveToRelative(0.83f, -0.83f, 0.75f, -2.23f, -0.25f, -2.95f)
                close()
                moveTo(19f, 12.5f)
                curveToRelative(0f, -0.83f, -0.67f, -1.5f, -1.5f, -1.5f)
                reflectiveCurveToRelative(-1.5f, 0.67f, -1.5f, 1.5f)
                verticalLineToRelative(6.75f)
                lineToRelative(-0.62f, -0.63f)
                curveToRelative(-0.68f, -0.68f, -1.77f, -0.85f, -2.56f, -0.28f)
                curveToRelative(-1.0f, 0.72f, -1.08f, 2.12f, -0.25f, 2.95f)
                lineToRelative(2.81f, 2.71f)
                horizontalLineToRelative(8.62f)
                verticalLineToRelative(-6.18f)
                lineToRelative(-5f, -2f)
                verticalLineToRelative(-3.32f)
                close()
                moveTo(24f, 3f)
                verticalLineToRelative(11f)
                horizontalLineToRelative(-3f)
                verticalLineToRelative(-1.5f)
                curveToRelative(0f, -0.95f, -0.39f, -1.8f, -1f, -2.43f)
                verticalLineToRelative(-2.07f)
                horizontalLineToRelative(-2f)
                verticalLineToRelative(1.05f)
                curveToRelative(-0.17f, -0.02f, -0.33f, -0.05f, -0.5f, -0.05f)
                curveToRelative(-0.54f, 0f, -1.04f, 0.13f, -1.5f, 0.35f)
                verticalLineToRelative(-1.35f)
                horizontalLineToRelative(-8f)
                verticalLineToRelative(1.35f)
                curveToRelative(-0.46f, -0.22f, -0.96f, -0.35f, -1.5f, -0.35f)
                curveToRelative(-0.17f, 0f, -0.34f, 0.03f, -0.5f, 0.05f)
                verticalLineToRelative(-1.05f)
                horizontalLineToRelative(-2f)
                verticalLineToRelative(2.07f)
                curveToRelative(-0.61f, 0.63f, -1f, 1.48f, -1f, 2.43f)
                verticalLineToRelative(1.5f)
                horizontalLineToRelative(-3f)
                verticalLineToRelative(-11f)
                curveToRelative(0f, -1.66f, 1.34f, -3f, 3f, -3f)
                horizontalLineToRelative(18f)
                curveToRelative(1.66f, 0f, 3f, 1.34f, 3f, 3f)
                close()
                moveTo(7f, 4f)
                horizontalLineToRelative(-3f)
                verticalLineToRelative(2f)
                horizontalLineToRelative(3f)
                close()
                moveTo(12f, 4f)
                horizontalLineToRelative(-3f)
                verticalLineToRelative(2f)
                horizontalLineToRelative(3f)
                close()
                moveTo(20f, 4f)
                horizontalLineToRelative(-6f)
                verticalLineToRelative(2f)
                horizontalLineToRelative(6f)
                close()
            }
        }.also { _HandsTypingKeyboard = it}
