package com.uxicons.compose.uicons.solid.straight

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import com.uxicons.compose.uicons.Icons
import com.uxicons.compose.uicons.core.UXIcon

private var _NetworkFirewall: ImageVector? = null

val Icons.Ss.NetworkFirewall: ImageVector
    get() = _NetworkFirewall ?: UXIcon(name = "NetworkFirewall") {
            path(fill = SolidColor(Color.Black)) {
                moveToRelative(13f, 18.18f)
                verticalLineToRelative(-3.33f)
                curveToRelative(1.72f, -0.45f, 3f, -2.0f, 3f, -3.86f)
                curveToRelative(0f, -2.32f, -2.74f, -4.07f, -4f, -5.33f)
                curveToRelative(-1.21f, 1.4f, -0.97f, 4f, -1.81f, 4f)
                curveToRelative(-0.4f, 0f, -0.86f, -1.39f, -0.86f, -1.39f)
                curveToRelative(-0.66f, 0.69f, -1.33f, 1.57f, -1.33f, 2.73f)
                curveToRelative(0f, 1.86f, 1.28f, 3.41f, 3f, 3.86f)
                verticalLineToRelative(3.33f)
                curveToRelative(-0.85f, 0.3f, -1.51f, 0.97f, -1.82f, 1.82f)
                horizontalLineToRelative(-9.18f)
                verticalLineToRelative(2f)
                horizontalLineToRelative(9.18f)
                curveToRelative(0.41f, 1.16f, 1.51f, 2f, 2.82f, 2f)
                reflectiveCurveToRelative(2.4f, -0.84f, 2.82f, -2f)
                horizontalLineToRelative(9.18f)
                verticalLineToRelative(-2f)
                horizontalLineToRelative(-9.18f)
                curveToRelative(-0.3f, -0.85f, -0.97f, -1.51f, -1.82f, -1.82f)
                close()
                moveTo(12.88f, 13.63f)
                curveToRelative(-0.24f, 0.24f, -0.56f, 0.37f, -0.88f, 0.37f)
                curveToRelative(-0.32f, 0f, -0.64f, -0.12f, -0.88f, -0.37f)
                curveToRelative(-0.49f, -0.49f, -0.49f, -1.28f, 0f, -1.77f)
                lineToRelative(0.88f, -0.88f)
                lineToRelative(0.88f, 0.88f)
                curveToRelative(0.49f, 0.49f, 0.49f, 1.28f, 0f, 1.77f)
                close()
                moveTo(2f, 10f)
                horizontalLineToRelative(-2f)
                verticalLineToRelative(-4f)
                horizontalLineToRelative(2f)
                close()
                moveTo(22f, 6f)
                horizontalLineToRelative(2f)
                verticalLineToRelative(4f)
                horizontalLineToRelative(-2f)
                close()
                moveTo(6f, 4f)
                horizontalLineToRelative(-6f)
                verticalLineToRelative(-1f)
                curveToRelative(0f, -1.65f, 1.35f, -3f, 3f, -3f)
                horizontalLineToRelative(3f)
                close()
                moveTo(24f, 3f)
                verticalLineToRelative(1f)
                horizontalLineToRelative(-6f)
                verticalLineToRelative(-4f)
                horizontalLineToRelative(3f)
                curveToRelative(1.65f, 0f, 3f, 1.35f, 3f, 3f)
                close()
                moveTo(4f, 6f)
                horizontalLineToRelative(4.75f)
                lineToRelative(-0.86f, 0.88f)
                curveToRelative(-0.39f, 0.4f, -1.44f, 1.5f, -1.78f, 3.12f)
                horizontalLineToRelative(-2.12f)
                close()
                moveTo(8f, 4f)
                verticalLineToRelative(-4f)
                horizontalLineToRelative(8f)
                verticalLineToRelative(4f)
                close()
                moveTo(15.35f, 6f)
                horizontalLineToRelative(4.65f)
                verticalLineToRelative(4f)
                horizontalLineToRelative(-2.1f)
                curveToRelative(-0.34f, -1.65f, -1.46f, -2.97f, -2.54f, -4f)
                close()
                moveTo(17.91f, 12f)
                horizontalLineToRelative(6.09f)
                verticalLineToRelative(4f)
                horizontalLineToRelative(-8.69f)
                curveToRelative(1.35f, -0.9f, 2.32f, -2.33f, 2.6f, -4f)
                close()
                moveTo(8.69f, 16f)
                horizontalLineToRelative(-8.69f)
                verticalLineToRelative(-4f)
                horizontalLineToRelative(6.09f)
                curveToRelative(0.28f, 1.67f, 1.25f, 3.1f, 2.6f, 4f)
                close()
            }
        }.also { _NetworkFirewall = it}
