package com.uxicons.compose.uicons.solid.straight

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import com.uxicons.compose.uicons.Icons
import com.uxicons.compose.uicons.core.UXIcon

private var _SnowBlowing: ImageVector? = null

val Icons.Ss.SnowBlowing: ImageVector
    get() = _SnowBlowing ?: UXIcon(name = "SnowBlowing") {
            path(fill = SolidColor(Color.Black)) {
                moveTo(15f, 20f)
                curveToRelative(-0.14f, 5.28f, -7.86f, 5.27f, -8f, 0f)
                lineTo(9f, 20f)
                arcToRelative(2f, 2f, 0f, isMoreThanHalf = true, isPositiveArc = false, 2f, -2f)
                lineTo(0f, 18f)
                lineTo(0f, 16f)
                lineTo(11f, 16f)
                arcTo(4f, 4f, 0f, isMoreThanHalf = false, isPositiveArc = true, 15f, 20f)
                close()
                moveTo(20f, 9f)
                curveToRelative(5.28f, -0.14f, 5.27f, -7.86f, 0f, -8f)
                arcToRelative(4f, 4f, 0f, isMoreThanHalf = false, isPositiveArc = false, -4f, 4f)
                horizontalLineToRelative(2f)
                arcToRelative(2f, 2f, 0f, isMoreThanHalf = true, isPositiveArc = true, 2f, 2f)
                lineTo(16f, 7f)
                arcToRelative(9.03f, 9.03f, 0f, isMoreThanHalf = false, isPositiveArc = true, -0.22f, 2f)
                close()
                moveTo(20f, 11f)
                lineTo(15.06f, 11f)
                arcToRelative(9.06f, 9.06f, 0f, isMoreThanHalf = false, isPositiveArc = true, -1.36f, 2f)
                lineTo(20f, 13f)
                arcToRelative(2f, 2f, 0f, isMoreThanHalf = true, isPositiveArc = true, -2f, 2f)
                lineTo(16f, 15f)
                curveToRelative(0.14f, 5.28f, 7.86f, 5.27f, 8f, 0f)
                arcTo(4f, 4f, 0f, isMoreThanHalf = false, isPositiveArc = false, 20f, 11f)
                close()
                moveTo(2.96f, 8.39f)
                lineTo(0.59f, 7.75f)
                lineTo(0.07f, 9.68f)
                lineToRelative(1.8f, 0.49f)
                lineToRelative(-0.49f, 1.8f)
                lineToRelative(1.93f, 0.52f)
                lineToRelative(0.64f, -2.37f)
                lineTo(6f, 8.95f)
                verticalLineToRelative(2.36f)
                lineTo(4.27f, 13.04f)
                lineToRelative(1.41f, 1.41f)
                lineTo(7f, 13.14f)
                lineToRelative(1.32f, 1.32f)
                lineToRelative(1.41f, -1.41f)
                lineTo(8f, 11.31f)
                lineTo(8f, 8.95f)
                lineToRelative(2.05f, 1.18f)
                lineToRelative(0.64f, 2.37f)
                lineToRelative(1.93f, -0.52f)
                lineToRelative(-0.49f, -1.8f)
                lineToRelative(1.8f, -0.49f)
                lineToRelative(-0.52f, -1.93f)
                lineToRelative(-2.36f, 0.64f)
                lineTo(9.01f, 7.22f)
                lineToRelative(2.03f, -1.17f)
                lineToRelative(2.37f, 0.64f)
                lineToRelative(0.52f, -1.93f)
                lineToRelative(-1.8f, -0.49f)
                lineToRelative(0.49f, -1.8f)
                lineTo(10.69f, 1.96f)
                lineToRelative(-0.64f, 2.36f)
                lineTo(8f, 5.49f)
                lineTo(8f, 3.13f)
                lineTo(9.73f, 1.4f)
                lineTo(8.32f, -0.01f)
                lineTo(7f, 1.3f)
                lineTo(5.68f, -0.01f)
                lineTo(4.27f, 1.4f)
                lineTo(6f, 3.13f)
                lineTo(6f, 5.49f)
                lineTo(3.95f, 4.32f)
                lineTo(3.31f, 1.96f)
                lineToRelative(-1.93f, 0.52f)
                lineToRelative(0.49f, 1.8f)
                lineToRelative(-1.8f, 0.49f)
                lineTo(0.59f, 6.7f)
                lineToRelative(2.37f, -0.64f)
                lineTo(4.99f, 7.22f)
                close()
            }
        }.also { _SnowBlowing = it}
