package com.uxicons.compose.uicons.regular.rounded

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import com.uxicons.compose.uicons.Icons
import com.uxicons.compose.uicons.core.UXIcon

private var _CraneBuilding: ImageVector? = null

val Icons.Rr.CraneBuilding: ImageVector
    get() = _CraneBuilding ?: UXIcon(name = "CraneBuilding") {
            path(fill = SolidColor(Color.Black)) {
                moveToRelative(24f, 11f)
                curveToRelative(0f, 0.55f, -0.45f, 1f, -1f, 1f)
                horizontalLineToRelative(-12f)
                curveToRelative(-0.55f, 0f, -1f, -0.45f, -1f, -1f)
                reflectiveCurveToRelative(0.45f, -1f, 1f, -1f)
                horizontalLineToRelative(1.03f)
                lineToRelative(3.27f, -4f)
                horizontalLineToRelative(-7.3f)
                verticalLineToRelative(0.3f)
                curveToRelative(0f, 0.94f, -0.76f, 1.7f, -1.7f, 1.7f)
                horizontalLineToRelative(-1.3f)
                verticalLineToRelative(14f)
                horizontalLineToRelative(2f)
                curveToRelative(0.55f, 0f, 1f, 0.45f, 1f, 1f)
                reflectiveCurveToRelative(-0.45f, 1f, -1f, 1f)
                horizontalLineToRelative(-6f)
                curveToRelative(-0.55f, 0f, -1f, -0.45f, -1f, -1f)
                reflectiveCurveToRelative(0.45f, -1f, 1f, -1f)
                horizontalLineToRelative(2f)
                verticalLineToRelative(-14.15f)
                curveToRelative(-0.59f, -0.27f, -1f, -0.86f, -1f, -1.54f)
                verticalLineToRelative(-0.3f)
                horizontalLineToRelative(-1f)
                curveToRelative(-0.55f, 0f, -1f, -0.45f, -1f, -1f)
                reflectiveCurveToRelative(0.45f, -1f, 1f, -1f)
                horizontalLineToRelative(1f)
                verticalLineToRelative(-0.3f)
                curveToRelative(0f, -0.69f, 0.41f, -1.28f, 1f, -1.54f)
                verticalLineToRelative(-1.16f)
                curveToRelative(0f, -0.55f, 0.45f, -1f, 1f, -1f)
                reflectiveCurveToRelative(1f, 0.45f, 1f, 1f)
                verticalLineToRelative(1.09f)
                curveToRelative(0.5f, 0.12f, 0.96f, 0.37f, 1.34f, 0.74f)
                lineToRelative(0.83f, 0.83f)
                curveToRelative(0.1f, 0.1f, 0.19f, 0.22f, 0.28f, 0.34f)
                horizontalLineToRelative(15.55f)
                curveToRelative(0.55f, 0f, 1f, 0.45f, 1f, 1f)
                reflectiveCurveToRelative(-0.45f, 1f, -1f, 1f)
                horizontalLineToRelative(-4.3f)
                lineToRelative(3.27f, 4f)
                horizontalLineToRelative(1.03f)
                curveToRelative(0.55f, 0f, 1f, 0.45f, 1f, 1f)
                close()
                moveTo(6f, 5.66f)
                curveToRelative(0f, -0.22f, -0.09f, -0.43f, -0.24f, -0.58f)
                lineToRelative(-0.83f, -0.83f)
                curveToRelative(-0.16f, -0.16f, -0.36f, -0.24f, -0.58f, -0.24f)
                horizontalLineToRelative(-0.34f)
                verticalLineToRelative(2f)
                horizontalLineToRelative(2f)
                close()
                moveTo(14.61f, 10f)
                horizontalLineToRelative(4.78f)
                lineToRelative(-2.39f, -2.92f)
                lineToRelative(-2.39f, 2.92f)
                close()
                moveTo(24f, 17.5f)
                verticalLineToRelative(3f)
                curveToRelative(0f, 1.93f, -1.57f, 3.5f, -3.5f, 3.5f)
                horizontalLineToRelative(-7f)
                curveToRelative(-1.93f, 0f, -3.5f, -1.57f, -3.5f, -3.5f)
                verticalLineToRelative(-3f)
                curveToRelative(0f, -1.93f, 1.57f, -3.5f, 3.5f, -3.5f)
                horizontalLineToRelative(7f)
                curveToRelative(1.93f, 0f, 3.5f, 1.57f, 3.5f, 3.5f)
                close()
                moveTo(22f, 17.5f)
                curveToRelative(0f, -0.83f, -0.67f, -1.5f, -1.5f, -1.5f)
                horizontalLineToRelative(-7f)
                curveToRelative(-0.83f, 0f, -1.5f, 0.67f, -1.5f, 1.5f)
                verticalLineToRelative(3f)
                curveToRelative(0f, 0.83f, 0.67f, 1.5f, 1.5f, 1.5f)
                horizontalLineToRelative(7f)
                curveToRelative(0.83f, 0f, 1.5f, -0.67f, 1.5f, -1.5f)
                close()
                moveTo(16.5f, 19.5f)
                verticalLineToRelative(-1f)
                curveToRelative(0f, -0.55f, -0.45f, -1f, -1f, -1f)
                horizontalLineToRelative(-1f)
                curveToRelative(-0.55f, 0f, -1f, 0.45f, -1f, 1f)
                verticalLineToRelative(1f)
                curveToRelative(0f, 0.55f, 0.45f, 1f, 1f, 1f)
                horizontalLineToRelative(1f)
                curveToRelative(0.55f, 0f, 1f, -0.45f, 1f, -1f)
                close()
                moveTo(20.5f, 19.5f)
                verticalLineToRelative(-1f)
                curveToRelative(0f, -0.55f, -0.45f, -1f, -1f, -1f)
                horizontalLineToRelative(-1f)
                curveToRelative(-0.55f, 0f, -1f, 0.45f, -1f, 1f)
                verticalLineToRelative(1f)
                curveToRelative(0f, 0.55f, 0.45f, 1f, 1f, 1f)
                horizontalLineToRelative(1f)
                curveToRelative(0.55f, 0f, 1f, -0.45f, 1f, -1f)
                close()
            }
        }.also { _CraneBuilding = it}
