package com.uxicons.compose.uicons.regular.rounded

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import com.uxicons.compose.uicons.Icons
import com.uxicons.compose.uicons.core.UXIcon

private var _TruckLadder: ImageVector? = null

val Icons.Rr.TruckLadder: ImageVector
    get() = _TruckLadder ?: UXIcon(name = "TruckLadder") {
            path(fill = SolidColor(Color.Black)) {
                moveTo(23.74f, 11.07f)
                lineToRelative(-1.11f, -3.33f)
                curveToRelative(-0.54f, -1.63f, -2.07f, -2.73f, -3.79f, -2.73f)
                horizontalLineToRelative(-0.84f)
                curveToRelative(-1.1f, 0f, -2f, 0.9f, -2f, 2f)
                verticalLineToRelative(4f)
                lineTo(4f, 11f)
                curveToRelative(-2.21f, 0f, -4f, 1.79f, -4f, 4f)
                verticalLineToRelative(4.49f)
                curveToRelative(0f, 1.94f, 1.57f, 3.51f, 3.51f, 3.51f)
                curveToRelative(0f, 0f, 0.23f, -0.01f, 0.35f, -0.02f)
                curveToRelative(0.83f, -0.08f, 1.56f, -0.48f, 2.12f, -1.07f)
                curveToRelative(0.77f, 0.81f, 1.91f, 1.25f, 3.15f, 1.03f)
                curveToRelative(1.69f, -0.3f, 2.87f, -1.86f, 2.87f, -3.58f)
                verticalLineToRelative(-0.36f)
                horizontalLineToRelative(4f)
                verticalLineToRelative(0.4f)
                curveToRelative(0f, 1.67f, 1.13f, 3.19f, 2.77f, 3.52f)
                curveToRelative(2.25f, 0.46f, 4.24f, -1.25f, 4.24f, -3.42f)
                verticalLineToRelative(-1.88f)
                curveToRelative(0.61f, -0.7f, 1f, -1.61f, 1f, -2.62f)
                verticalLineToRelative(-2.35f)
                curveToRelative(0f, -0.65f, -0.21f, -1.44f, -0.26f, -1.58f)
                close()
                moveTo(5f, 19.5f)
                curveToRelative(0f, 0.83f, -0.67f, 1.5f, -1.5f, 1.5f)
                reflectiveCurveToRelative(-1.5f, -0.67f, -1.5f, -1.5f)
                verticalLineToRelative(-0.5f)
                horizontalLineToRelative(3f)
                verticalLineToRelative(0.5f)
                close()
                moveTo(10f, 19.5f)
                curveToRelative(0f, 0.83f, -0.67f, 1.5f, -1.5f, 1.5f)
                reflectiveCurveToRelative(-1.5f, -0.67f, -1.5f, -1.5f)
                curveToRelative(0f, -0.02f, -0.01f, -0.03f, -0.01f, -0.04f)
                curveToRelative(0f, -0.03f, 0.01f, -0.46f, 0.01f, -0.46f)
                horizontalLineToRelative(3f)
                verticalLineToRelative(0.5f)
                close()
                moveTo(16f, 17f)
                lineTo(2f, 17f)
                verticalLineToRelative(-2f)
                curveToRelative(0f, -1.1f, 0.9f, -2f, 2f, -2f)
                horizontalLineToRelative(12f)
                verticalLineToRelative(4f)
                close()
                moveTo(18f, 7f)
                horizontalLineToRelative(0.84f)
                curveToRelative(0.86f, 0f, 1.62f, 0.55f, 1.9f, 1.37f)
                lineToRelative(0.88f, 2.63f)
                horizontalLineToRelative(-3.61f)
                lineTo(18f, 7f)
                close()
                moveTo(21f, 19.5f)
                curveToRelative(0f, 0.83f, -0.67f, 1.5f, -1.5f, 1.5f)
                reflectiveCurveToRelative(-1.5f, -0.67f, -1.5f, -1.5f)
                verticalLineToRelative(-0.5f)
                horizontalLineToRelative(2f)
                curveToRelative(0.35f, 0f, 0.68f, -0.06f, 1f, -0.14f)
                verticalLineToRelative(0.64f)
                close()
                moveTo(22f, 15f)
                curveToRelative(0f, 1.1f, -0.9f, 2f, -2f, 2f)
                horizontalLineToRelative(-2f)
                verticalLineToRelative(-4f)
                horizontalLineToRelative(4f)
                verticalLineToRelative(2f)
                close()
                moveTo(1f, 7f)
                curveToRelative(-0.55f, 0f, -1f, 0.45f, -1f, 1f)
                reflectiveCurveToRelative(0.45f, 1f, 1f, 1f)
                lineTo(13f, 9f)
                curveToRelative(0.55f, 0f, 1f, -0.45f, 1f, -1f)
                reflectiveCurveToRelative(-0.45f, -1f, -1f, -1f)
                horizontalLineToRelative(-1f)
                lineTo(12f, 3f)
                horizontalLineToRelative(1f)
                curveToRelative(0.55f, 0f, 1f, -0.45f, 1f, -1f)
                reflectiveCurveToRelative(-0.45f, -1f, -1f, -1f)
                lineTo(1f, 1f)
                curveToRelative(-0.55f, 0f, -1f, 0.45f, -1f, 1f)
                reflectiveCurveToRelative(0.45f, 1f, 1f, 1f)
                horizontalLineToRelative(1f)
                lineTo(2f, 7f)
                lineTo(1f, 7f)
                close()
                moveTo(8f, 3f)
                horizontalLineToRelative(2f)
                lineTo(10f, 7f)
                horizontalLineToRelative(-2f)
                lineTo(8f, 3f)
                close()
                moveTo(4f, 3f)
                horizontalLineToRelative(2f)
                lineTo(6f, 7f)
                horizontalLineToRelative(-2f)
                lineTo(4f, 3f)
                close()
            }
        }.also { _TruckLadder = it}
