package com.uxicons.compose.uicons.regular.rounded

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import com.uxicons.compose.uicons.Icons
import com.uxicons.compose.uicons.core.UXIcon

private var _Tuesday: ImageVector? = null

val Icons.Rr.Tuesday: ImageVector
    get() = _Tuesday ?: UXIcon(name = "Tuesday") {
            path(fill = SolidColor(Color.Black)) {
                moveToRelative(19f, 2f)
                horizontalLineToRelative(-1f)
                verticalLineToRelative(-1f)
                curveToRelative(0f, -0.55f, -0.45f, -1f, -1f, -1f)
                reflectiveCurveToRelative(-1f, 0.45f, -1f, 1f)
                verticalLineToRelative(1f)
                horizontalLineToRelative(-8f)
                verticalLineToRelative(-1f)
                curveToRelative(0f, -0.55f, -0.45f, -1f, -1f, -1f)
                reflectiveCurveToRelative(-1f, 0.45f, -1f, 1f)
                verticalLineToRelative(1f)
                horizontalLineToRelative(-1f)
                curveTo(2.24f, 2f, 0f, 4.24f, 0f, 7f)
                verticalLineToRelative(12f)
                curveToRelative(0f, 2.76f, 2.24f, 5f, 5f, 5f)
                horizontalLineToRelative(2f)
                curveToRelative(0.55f, 0f, 1f, -0.45f, 1f, -1f)
                reflectiveCurveToRelative(-0.45f, -1f, -1f, -1f)
                horizontalLineToRelative(-2f)
                curveToRelative(-1.65f, 0f, -3f, -1.35f, -3f, -3f)
                verticalLineToRelative(-9f)
                horizontalLineToRelative(20f)
                verticalLineToRelative(3f)
                curveToRelative(0f, 0.55f, 0.45f, 1f, 1f, 1f)
                reflectiveCurveToRelative(1f, -0.45f, 1f, -1f)
                verticalLineToRelative(-6f)
                curveToRelative(0f, -2.76f, -2.24f, -5f, -5f, -5f)
                close()
                moveTo(22f, 8f)
                lineTo(2f, 8f)
                verticalLineToRelative(-1f)
                curveToRelative(0f, -1.65f, 1.35f, -3f, 3f, -3f)
                horizontalLineToRelative(14f)
                curveToRelative(1.65f, 0f, 3f, 1.35f, 3f, 3f)
                verticalLineToRelative(1f)
                close()
                moveTo(19.34f, 16.77f)
                verticalLineToRelative(4.93f)
                curveToRelative(0f, 1.35f, -1.16f, 2.43f, -2.54f, 2.29f)
                curveToRelative(-1.2f, -0.12f, -2.06f, -1.22f, -2.06f, -2.42f)
                verticalLineToRelative(-4.8f)
                curveToRelative(0f, -0.44f, 0.36f, -0.8f, 0.8f, -0.8f)
                reflectiveCurveToRelative(0.8f, 0.36f, 0.8f, 0.8f)
                verticalLineToRelative(4.93f)
                curveToRelative(0f, 0.39f, 0.31f, 0.7f, 0.7f, 0.7f)
                reflectiveCurveToRelative(0.7f, -0.31f, 0.7f, -0.7f)
                verticalLineToRelative(-4.93f)
                curveToRelative(0f, -0.44f, 0.36f, -0.8f, 0.8f, -0.8f)
                reflectiveCurveToRelative(0.8f, 0.36f, 0.8f, 0.8f)
                close()
                moveTo(13.76f, 16.77f)
                curveToRelative(0f, 0.44f, -0.36f, 0.8f, -0.8f, 0.8f)
                horizontalLineToRelative(-0.95f)
                verticalLineToRelative(5.6f)
                curveToRelative(0f, 0.44f, -0.36f, 0.8f, -0.8f, 0.8f)
                reflectiveCurveToRelative(-0.8f, -0.36f, -0.8f, -0.8f)
                verticalLineToRelative(-5.6f)
                horizontalLineToRelative(-0.85f)
                curveToRelative(-0.44f, 0f, -0.8f, -0.36f, -0.8f, -0.8f)
                reflectiveCurveToRelative(0.36f, -0.8f, 0.8f, -0.8f)
                horizontalLineToRelative(3.4f)
                curveToRelative(0.44f, 0f, 0.8f, 0.36f, 0.8f, 0.8f)
                close()
                moveTo(22.1f, 17.57f)
                verticalLineToRelative(1.65f)
                horizontalLineToRelative(1.1f)
                curveToRelative(0.44f, 0f, 0.8f, 0.36f, 0.8f, 0.8f)
                reflectiveCurveToRelative(-0.36f, 0.8f, -0.8f, 0.8f)
                horizontalLineToRelative(-1.1f)
                verticalLineToRelative(1.55f)
                horizontalLineToRelative(1.1f)
                curveToRelative(0.44f, 0f, 0.8f, 0.36f, 0.8f, 0.8f)
                reflectiveCurveToRelative(-0.36f, 0.8f, -0.8f, 0.8f)
                horizontalLineToRelative(-1.9f)
                curveToRelative(-0.44f, 0f, -0.8f, -0.36f, -0.8f, -0.8f)
                verticalLineToRelative(-6.4f)
                curveToRelative(0f, -0.44f, 0.36f, -0.8f, 0.8f, -0.8f)
                horizontalLineToRelative(1.9f)
                curveToRelative(0.44f, 0f, 0.8f, 0.36f, 0.8f, 0.8f)
                reflectiveCurveToRelative(-0.36f, 0.8f, -0.8f, 0.8f)
                horizontalLineToRelative(-1.1f)
                close()
            }
        }.also { _Tuesday = it}
