package com.uxicons.compose.uicons.thin.straight

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import com.uxicons.compose.uicons.Icons
import com.uxicons.compose.uicons.core.UXIcon

private var _Builder: ImageVector? = null

val Icons.Ts.Builder: ImageVector
    get() = _Builder ?: UXIcon(name = "Builder") {
            path(fill = SolidColor(Color.Black)) {
                moveToRelative(3f, 9f)
                curveToRelative(0f, 3.31f, 2.69f, 6f, 6f, 6f)
                reflectiveCurveToRelative(6f, -2.69f, 6f, -6.0f)
                lineToRelative(-0.01f, -2.0f)
                horizontalLineToRelative(0.99f)
                verticalLineToRelative(-1f)
                horizontalLineToRelative(-1.0f)
                lineToRelative(-0.0f, -0.55f)
                curveToRelative(0f, -3.0f, -2.44f, -5.45f, -5.45f, -5.45f)
                horizontalLineToRelative(-1.1f)
                curveTo(5.43f, 0f, 2.99f, 2.44f, 2.99f, 5.45f)
                lineToRelative(0.0f, 0.55f)
                horizontalLineToRelative(-1.0f)
                verticalLineToRelative(1f)
                horizontalLineToRelative(1.01f)
                lineToRelative(0.01f, 2f)
                close()
                moveTo(14f, 9f)
                curveToRelative(0f, 2.76f, -2.24f, 5f, -5f, 5f)
                reflectiveCurveToRelative(-5f, -2.24f, -5f, -5.0f)
                lineToRelative(-0.01f, -2.0f)
                horizontalLineToRelative(10f)
                lineToRelative(0.01f, 2f)
                close()
                moveTo(3.99f, 5.45f)
                curveToRelative(0f, -1.94f, 1.26f, -3.58f, 3f, -4.19f)
                verticalLineToRelative(2.74f)
                horizontalLineToRelative(1f)
                lineTo(7.99f, 1.04f)
                curveToRelative(0.15f, -0.01f, 0.3f, -0.04f, 0.45f, -0.04f)
                horizontalLineToRelative(1.1f)
                curveToRelative(0.15f, 0f, 0.3f, 0.03f, 0.45f, 0.05f)
                verticalLineToRelative(2.95f)
                horizontalLineToRelative(1f)
                lineTo(10.99f, 1.26f)
                curveToRelative(1.74f, 0.6f, 3f, 2.24f, 3f, 4.19f)
                lineToRelative(0.0f, 0.55f)
                lineTo(3.99f, 6f)
                lineToRelative(-0.0f, -0.55f)
                close()
                moveTo(12f, 17f)
                horizontalLineToRelative(-7f)
                curveToRelative(-2.21f, 0f, -4f, 1.79f, -4f, 4f)
                verticalLineToRelative(3f)
                lineTo(0f, 24f)
                verticalLineToRelative(-3f)
                curveToRelative(0f, -2.76f, 2.24f, -5f, 5f, -5f)
                horizontalLineToRelative(7f)
                verticalLineToRelative(1f)
                close()
                moveTo(17f, 14f)
                verticalLineToRelative(3f)
                horizontalLineToRelative(-3f)
                verticalLineToRelative(3f)
                horizontalLineToRelative(-3f)
                verticalLineToRelative(4f)
                horizontalLineToRelative(13f)
                verticalLineToRelative(-10f)
                horizontalLineToRelative(-7f)
                close()
                moveTo(18f, 15f)
                horizontalLineToRelative(5f)
                verticalLineToRelative(2f)
                horizontalLineToRelative(-5f)
                verticalLineToRelative(-2f)
                close()
                moveTo(15f, 18f)
                horizontalLineToRelative(5f)
                verticalLineToRelative(2f)
                horizontalLineToRelative(-5f)
                verticalLineToRelative(-2f)
                close()
                moveTo(17f, 23f)
                horizontalLineToRelative(-5f)
                verticalLineToRelative(-2f)
                horizontalLineToRelative(5f)
                verticalLineToRelative(2f)
                close()
                moveTo(23f, 23f)
                horizontalLineToRelative(-5f)
                verticalLineToRelative(-2f)
                horizontalLineToRelative(5f)
                verticalLineToRelative(2f)
                close()
                moveTo(23f, 20f)
                horizontalLineToRelative(-2f)
                verticalLineToRelative(-2f)
                horizontalLineToRelative(2f)
                verticalLineToRelative(2f)
                close()
            }
        }.also { _Builder = it}
