package com.uxicons.compose.uicons.thin.straight

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import com.uxicons.compose.uicons.Icons
import com.uxicons.compose.uicons.core.UXIcon

private var _ClothingRack: ImageVector? = null

val Icons.Ts.ClothingRack: ImageVector
    get() = _ClothingRack ?: UXIcon(name = "ClothingRack") {
            path(fill = SolidColor(Color.Black)) {
                moveTo(1.0f, 3f)
                lineToRelative(0.0f, 21f)
                lineTo(0f, 24f)
                lineTo(-0.0f, 0f)
                lineTo(1.0f, 0f)
                lineTo(1.0f, 2f)
                lineTo(7f, 2f)
                verticalLineToRelative(1f)
                lineTo(1.0f, 3f)
                close()
                moveTo(15f, 3f)
                lineTo(15f, 7f)
                horizontalLineToRelative(1.75f)
                curveToRelative(2.58f, 0f, 4.25f, 1.49f, 4.25f, 3.8f)
                verticalLineToRelative(2.2f)
                horizontalLineToRelative(-2f)
                verticalLineToRelative(7f)
                lineTo(5f, 20f)
                verticalLineToRelative(-7f)
                lineTo(3f, 13f)
                verticalLineToRelative(-2.2f)
                curveToRelative(0f, -2.31f, 1.67f, -3.8f, 4.25f, -3.8f)
                horizontalLineToRelative(1.75f)
                lineTo(9f, 2f)
                horizontalLineToRelative(3f)
                verticalLineToRelative(1f)
                horizontalLineToRelative(-2f)
                lineTo(10f, 7f)
                horizontalLineToRelative(4f)
                lineTo(14f, 2f)
                horizontalLineToRelative(9f)
                lineTo(23f, 0f)
                reflectiveCurveToRelative(1f, 0f, 1f, 0f)
                lineToRelative(0.0f, 24f)
                horizontalLineToRelative(-1f)
                lineToRelative(-0.0f, -21f)
                lineTo(15f, 3f)
                close()
                moveTo(9.2f, 8f)
                horizontalLineToRelative(-1.92f)
                curveToRelative(0.26f, 0.46f, 0.69f, 0.78f, 1.2f, 0.92f)
                curveToRelative(0.19f, -0.35f, 0.43f, -0.66f, 0.73f, -0.92f)
                close()
                moveTo(10f, 19f)
                verticalLineToRelative(-6f)
                horizontalLineToRelative(-2f)
                verticalLineToRelative(-2.2f)
                curveToRelative(0f, -0.33f, 0.04f, -0.64f, 0.11f, -0.94f)
                curveToRelative(-0.85f, -0.27f, -1.55f, -0.9f, -1.89f, -1.75f)
                curveToRelative(-0.99f, 0.22f, -2.23f, 0.86f, -2.23f, 2.69f)
                verticalLineToRelative(1.2f)
                horizontalLineToRelative(2f)
                verticalLineToRelative(7f)
                horizontalLineToRelative(4f)
                close()
                moveTo(17.3f, 8.03f)
                curveToRelative(-0.43f, 1.17f, -1.53f, 1.97f, -2.8f, 1.97f)
                reflectiveCurveToRelative(-2.37f, -0.8f, -2.8f, -1.97f)
                curveToRelative(-1.02f, 0.12f, -2.7f, 0.63f, -2.7f, 2.77f)
                verticalLineToRelative(1.2f)
                horizontalLineToRelative(2f)
                verticalLineToRelative(7f)
                horizontalLineToRelative(7f)
                verticalLineToRelative(-7f)
                horizontalLineToRelative(2f)
                verticalLineToRelative(-1.2f)
                curveToRelative(0f, -2.14f, -1.68f, -2.65f, -2.7f, -2.77f)
                close()
                moveTo(12.78f, 8f)
                curveToRelative(0.35f, 0.61f, 0.99f, 1f, 1.72f, 1f)
                reflectiveCurveToRelative(1.37f, -0.39f, 1.72f, -1f)
                horizontalLineToRelative(-3.44f)
                close()
            }
        }.also { _ClothingRack = it}
