package com.uxicons.compose.uicons.thin.straight

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import com.uxicons.compose.uicons.Icons
import com.uxicons.compose.uicons.core.UXIcon

private var _GridDividers: ImageVector? = null

val Icons.Ts.GridDividers: ImageVector
    get() = _GridDividers ?: UXIcon(name = "GridDividers") {
            path(fill = SolidColor(Color.Black)) {
                moveTo(24f, 1f)
                lineTo(0f, 1f)
                lineTo(0f, 0f)
                lineTo(24f, 0f)
                lineTo(24f, 1f)
                close()
                moveTo(24f, 12f)
                lineTo(0f, 12f)
                verticalLineToRelative(1f)
                lineTo(24f, 13f)
                verticalLineToRelative(-1f)
                close()
                moveTo(6f, 4f)
                lineTo(0f, 4f)
                verticalLineToRelative(6f)
                lineTo(6f, 10f)
                lineTo(6f, 4f)
                close()
                moveTo(1f, 5f)
                lineTo(5f, 5f)
                verticalLineToRelative(4f)
                lineTo(1f, 9f)
                lineTo(1f, 5f)
                close()
                moveTo(15f, 4f)
                horizontalLineToRelative(-6f)
                verticalLineToRelative(6f)
                horizontalLineToRelative(6f)
                lineTo(15f, 4f)
                close()
                moveTo(10f, 5f)
                horizontalLineToRelative(4f)
                verticalLineToRelative(4f)
                horizontalLineToRelative(-4f)
                lineTo(10f, 5f)
                close()
                moveTo(24f, 4f)
                horizontalLineToRelative(-6f)
                verticalLineToRelative(6f)
                horizontalLineToRelative(6f)
                lineTo(24f, 4f)
                close()
                moveTo(19f, 5f)
                horizontalLineToRelative(4f)
                verticalLineToRelative(4f)
                horizontalLineToRelative(-4f)
                lineTo(19f, 5f)
                close()
                moveTo(6f, 16f)
                lineTo(0f, 16f)
                verticalLineToRelative(6f)
                lineTo(6f, 22f)
                verticalLineToRelative(-6f)
                close()
                moveTo(1f, 17f)
                lineTo(5f, 17f)
                verticalLineToRelative(4f)
                lineTo(1f, 21f)
                verticalLineToRelative(-4f)
                close()
                moveTo(15f, 16f)
                horizontalLineToRelative(-6f)
                verticalLineToRelative(6f)
                horizontalLineToRelative(6f)
                verticalLineToRelative(-6f)
                close()
                moveTo(10f, 17f)
                horizontalLineToRelative(4f)
                verticalLineToRelative(4f)
                horizontalLineToRelative(-4f)
                verticalLineToRelative(-4f)
                close()
                moveTo(24f, 16f)
                horizontalLineToRelative(-6f)
                verticalLineToRelative(6f)
                horizontalLineToRelative(6f)
                verticalLineToRelative(-6f)
                close()
                moveTo(19f, 17f)
                horizontalLineToRelative(4f)
                verticalLineToRelative(4f)
                horizontalLineToRelative(-4f)
                verticalLineToRelative(-4f)
                close()
            }
        }.also { _GridDividers = it}
