package com.uxicons.compose.uicons.thin.straight

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import com.uxicons.compose.uicons.Icons
import com.uxicons.compose.uicons.core.UXIcon

private var _PersonMilitaryRifle: ImageVector? = null

val Icons.Ts.PersonMilitaryRifle: ImageVector
    get() = _PersonMilitaryRifle ?: UXIcon(name = "PersonMilitaryRifle") {
            path(fill = SolidColor(Color.Black)) {
                moveTo(24f, 8.5f)
                verticalLineToRelative(-0.5f)
                horizontalLineToRelative(-3f)
                verticalLineToRelative(0.5f)
                curveToRelative(0f, 1.88f, -0.98f, 2.76f, -2f, 3.17f)
                lineTo(19f, 0f)
                horizontalLineToRelative(-3f)
                lineTo(16f, 2f)
                horizontalLineToRelative(-1f)
                verticalLineToRelative(1f)
                horizontalLineToRelative(1f)
                lineTo(16f, 24f)
                horizontalLineToRelative(5f)
                verticalLineToRelative(-1.5f)
                lineToRelative(-1.25f, -5.05f)
                lineToRelative(4.25f, 0.86f)
                verticalLineToRelative(-3.06f)
                lineToRelative(-3.74f, -0.77f)
                curveToRelative(3.68f, -1.51f, 3.74f, -5.94f, 3.74f, -5.99f)
                close()
                moveTo(17f, 1f)
                horizontalLineToRelative(1f)
                lineTo(18f, 14f)
                horizontalLineToRelative(-1f)
                lineTo(17f, 1f)
                close()
                moveTo(20f, 22.56f)
                verticalLineToRelative(0.44f)
                horizontalLineToRelative(-3f)
                lineTo(17f, 15f)
                horizontalLineToRelative(1.16f)
                lineToRelative(1.84f, 7.56f)
                close()
                moveTo(23f, 16.07f)
                verticalLineToRelative(1.02f)
                lineToRelative(-3.52f, -0.72f)
                lineToRelative(-0.27f, -1.08f)
                lineToRelative(3.79f, 0.77f)
                close()
                moveTo(19f, 13.85f)
                verticalLineToRelative(-1.11f)
                curveToRelative(1.19f, -0.38f, 2.79f, -1.33f, 2.98f, -3.74f)
                horizontalLineToRelative(0.99f)
                curveToRelative(-0.13f, 1.2f, -0.78f, 4.14f, -3.97f, 4.84f)
                close()
                moveTo(3.74f, 13.0f)
                lineTo(0.05f, 20.79f)
                lineToRelative(0.9f, 0.43f)
                lineToRelative(3.69f, -7.78f)
                curveToRelative(0.1f, -0.2f, 0.22f, -0.38f, 0.36f, -0.54f)
                verticalLineToRelative(11.11f)
                lineTo(14f, 24.0f)
                verticalLineToRelative(-1f)
                lineTo(6f, 23.0f)
                verticalLineToRelative(-1f)
                lineTo(14f, 22.0f)
                verticalLineToRelative(-1f)
                lineTo(7.94f, 21.0f)
                lineToRelative(6.06f, -7.88f)
                verticalLineToRelative(-2.12f)
                lineTo(6.9f, 11.0f)
                curveToRelative(-1.35f, 0f, -2.59f, 0.79f, -3.16f, 2.0f)
                close()
                moveTo(13.62f, 12.0f)
                lineToRelative(-6.94f, 9f)
                horizontalLineToRelative(-0.67f)
                verticalLineToRelative(-1.15f)
                lineToRelative(6.24f, -7.85f)
                horizontalLineToRelative(1.38f)
                close()
                moveTo(6.0f, 18.23f)
                verticalLineToRelative(-6.04f)
                curveToRelative(0.28f, -0.11f, 0.58f, -0.19f, 0.9f, -0.19f)
                horizontalLineToRelative(4.01f)
                lineToRelative(-4.91f, 6.23f)
                close()
                moveTo(13.31f, 0.51f)
                lineTo(7.3f, 0.0f)
                curveToRelative(-1.08f, -0.08f, -1.97f, 1.0f, -1.66f, 2.09f)
                lineToRelative(0.37f, 1.0f)
                verticalLineToRelative(1.91f)
                curveToRelative(0f, 2.21f, 1.79f, 4f, 4f, 4f)
                reflectiveCurveToRelative(4f, -1.79f, 4f, -4f)
                verticalLineToRelative(-1.5f)
                lineToRelative(0.47f, -1.41f)
                curveToRelative(0.22f, -0.7f, -0.39f, -1.57f, -1.15f, -1.57f)
                close()
                moveTo(13f, 5f)
                curveToRelative(0f, 1.65f, -1.35f, 3f, -3f, 3f)
                reflectiveCurveToRelative(-3f, -1.35f, -3f, -3f)
                verticalLineToRelative(-1f)
                horizontalLineToRelative(6f)
                verticalLineToRelative(1f)
                close()
                moveTo(13.07f, 3f)
                lineTo(7f, 3f)
                lineToRelative(-0.41f, -1.2f)
                curveToRelative(-0.12f, -0.39f, 0.25f, -0.83f, 0.64f, -0.8f)
                lineToRelative(6.03f, 0.51f)
                curveToRelative(0.14f, -0.03f, 0.26f, 0.21f, 0.26f, 0.26f)
                lineToRelative(-0.45f, 1.23f)
                close()
            }
        }.also { _PersonMilitaryRifle = it}
