package com.uxicons.compose.uicons.thin.straight

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import com.uxicons.compose.uicons.Icons
import com.uxicons.compose.uicons.core.UXIcon

private var _QrcodeWifi: ImageVector? = null

val Icons.Ts.QrcodeWifi: ImageVector
    get() = _QrcodeWifi ?: UXIcon(name = "QrcodeWifi") {
            path(fill = SolidColor(Color.Black)) {
                moveToRelative(19f, 22f)
                horizontalLineToRelative(2f)
                verticalLineToRelative(2f)
                horizontalLineToRelative(-2f)
                close()
                moveTo(22f, 21f)
                horizontalLineToRelative(2f)
                verticalLineToRelative(-2f)
                horizontalLineToRelative(-2f)
                close()
                moveTo(19f, 21f)
                horizontalLineToRelative(2f)
                verticalLineToRelative(-2f)
                horizontalLineToRelative(-2f)
                close()
                moveTo(13f, 13f)
                horizontalLineToRelative(5f)
                verticalLineToRelative(5f)
                horizontalLineToRelative(-5f)
                close()
                moveTo(14f, 17f)
                horizontalLineToRelative(3f)
                verticalLineToRelative(-3f)
                horizontalLineToRelative(-3f)
                close()
                moveTo(13f, 19f)
                horizontalLineToRelative(5f)
                verticalLineToRelative(5f)
                horizontalLineToRelative(-5f)
                close()
                moveTo(14f, 23f)
                horizontalLineToRelative(3f)
                verticalLineToRelative(-3f)
                horizontalLineToRelative(-3f)
                close()
                moveTo(24f, 13f)
                verticalLineToRelative(5f)
                horizontalLineToRelative(-5f)
                verticalLineToRelative(-5f)
                close()
                moveTo(23f, 14f)
                horizontalLineToRelative(-3f)
                verticalLineToRelative(3f)
                horizontalLineToRelative(3f)
                close()
                moveTo(15f, 16f)
                horizontalLineToRelative(1f)
                verticalLineToRelative(-1f)
                horizontalLineToRelative(-1f)
                close()
                moveTo(22f, 15f)
                horizontalLineToRelative(-1f)
                verticalLineToRelative(1f)
                horizontalLineToRelative(1f)
                close()
                moveTo(15f, 22f)
                horizontalLineToRelative(1f)
                verticalLineToRelative(-1f)
                horizontalLineToRelative(-1f)
                close()
                moveTo(17.22f, 7.78f)
                curveToRelative(-1.79f, -1.79f, -4.18f, -2.78f, -6.72f, -2.78f)
                reflectiveCurveToRelative(-4.92f, 0.99f, -6.72f, 2.78f)
                lineToRelative(0.71f, 0.71f)
                curveToRelative(1.6f, -1.6f, 3.74f, -2.49f, 6.01f, -2.49f)
                reflectiveCurveToRelative(4.41f, 0.88f, 6.01f, 2.49f)
                close()
                moveTo(5.9f, 9.9f)
                lineTo(6.61f, 10.61f)
                curveToRelative(2.15f, -2.15f, 5.63f, -2.15f, 7.78f, 0f)
                lineToRelative(0.71f, -0.71f)
                curveToRelative(-2.53f, -2.53f, -6.66f, -2.53f, -9.19f, 0f)
                close()
                moveTo(8.03f, 12.03f)
                lineTo(8.73f, 12.73f)
                curveToRelative(0.94f, -0.94f, 2.59f, -0.94f, 3.54f, 0f)
                lineToRelative(0.71f, -0.71f)
                curveToRelative(-1.32f, -1.32f, -3.63f, -1.32f, -4.95f, 0f)
                close()
                moveTo(10.5f, 14.0f)
                curveToRelative(-0.55f, 0f, -1f, 0.45f, -1f, 1f)
                reflectiveCurveToRelative(0.45f, 1f, 1f, 1f)
                reflectiveCurveToRelative(1f, -0.45f, 1f, -1f)
                reflectiveCurveToRelative(-0.45f, -1f, -1f, -1f)
                close()
                moveTo(1f, 10.5f)
                curveToRelative(0f, -5.24f, 4.26f, -9.5f, 9.5f, -9.5f)
                reflectiveCurveToRelative(9.5f, 4.26f, 9.5f, 9.5f)
                curveToRelative(0f, 0.17f, -0.02f, 0.33f, -0.03f, 0.5f)
                horizontalLineToRelative(1f)
                curveToRelative(0.01f, -0.17f, 0.03f, -0.33f, 0.03f, -0.5f)
                curveToRelative(0f, -5.79f, -4.71f, -10.5f, -10.5f, -10.5f)
                reflectiveCurveToRelative(-10.5f, 4.71f, -10.5f, 10.5f)
                reflectiveCurveToRelative(4.71f, 10.5f, 10.5f, 10.5f)
                curveToRelative(0.17f, 0f, 0.33f, -0.02f, 0.5f, -0.03f)
                verticalLineToRelative(-1f)
                curveToRelative(-0.17f, 0.01f, -0.33f, 0.03f, -0.5f, 0.03f)
                curveToRelative(-5.24f, 0f, -9.5f, -4.26f, -9.5f, -9.5f)
                close()
            }
        }.also { _QrcodeWifi = it}
