package com.uxicons.compose.uicons.thin.straight

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import com.uxicons.compose.uicons.Icons
import com.uxicons.compose.uicons.core.UXIcon

private var _Stadium: ImageVector? = null

val Icons.Ts.Stadium: ImageVector
    get() = _Stadium ?: UXIcon(name = "Stadium") {
            path(fill = SolidColor(Color.Black)) {
                moveToRelative(20f, 7f)
                verticalLineToRelative(-3.04f)
                lineToRelative(3.53f, -1.97f)
                lineToRelative(-3.59f, -2f)
                horizontalLineToRelative(-0.94f)
                verticalLineToRelative(7f)
                horizontalLineToRelative(-6.5f)
                verticalLineToRelative(-3.04f)
                lineToRelative(3.53f, -1.97f)
                lineToRelative(-3.59f, -2f)
                horizontalLineToRelative(-0.94f)
                verticalLineToRelative(7f)
                horizontalLineToRelative(-6.5f)
                verticalLineToRelative(-3.04f)
                lineToRelative(3.53f, -1.97f)
                lineToRelative(-3.59f, -2f)
                horizontalLineToRelative(-0.94f)
                verticalLineToRelative(7f)
                horizontalLineToRelative(-4f)
                verticalLineToRelative(3.5f)
                lineToRelative(3f, 9.08f)
                verticalLineToRelative(4.42f)
                horizontalLineToRelative(8f)
                verticalLineToRelative(-3f)
                curveToRelative(0f, -0.55f, 0.45f, -1f, 1f, -1f)
                reflectiveCurveToRelative(1f, 0.45f, 1f, 1f)
                verticalLineToRelative(3f)
                horizontalLineToRelative(8f)
                verticalLineToRelative(-4.42f)
                lineToRelative(2.97f, -8.92f)
                lineToRelative(0.03f, -3.66f)
                close()
                moveTo(20f, 1.18f)
                lineTo(21.47f, 2f)
                lineTo(20f, 2.82f)
                close()
                moveTo(12.5f, 1.18f)
                lineTo(13.97f, 2f)
                lineTo(12.5f, 2.82f)
                close()
                moveTo(5f, 1.18f)
                lineTo(6.47f, 2f)
                lineTo(5f, 2.82f)
                close()
                moveTo(17.4f, 8f)
                lineTo(16.33f, 14f)
                horizontalLineToRelative(-3.83f)
                verticalLineToRelative(-6f)
                close()
                moveTo(11.5f, 14f)
                horizontalLineToRelative(-3.83f)
                lineToRelative(-1.08f, -6f)
                horizontalLineToRelative(4.9f)
                close()
                moveTo(1f, 8f)
                horizontalLineToRelative(4.59f)
                lineToRelative(1.08f, 6f)
                horizontalLineToRelative(-4.49f)
                lineToRelative(-1.18f, -3.58f)
                close()
                moveTo(20.03f, 19.34f)
                lineTo(20f, 23f)
                horizontalLineToRelative(-6f)
                verticalLineToRelative(-2f)
                curveToRelative(0f, -1.1f, -0.9f, -2f, -2f, -2f)
                reflectiveCurveToRelative(-2f, 0.9f, -2f, 2f)
                verticalLineToRelative(2f)
                horizontalLineToRelative(-6f)
                verticalLineToRelative(-3.5f)
                lineToRelative(-1.49f, -4.5f)
                horizontalLineToRelative(18.96f)
                close()
                moveTo(23f, 10.42f)
                lineTo(21.81f, 14f)
                horizontalLineToRelative(-4.48f)
                lineToRelative(1.08f, -6f)
                horizontalLineToRelative(4.59f)
                close()
            }
        }.also { _Stadium = it}
