package com.uxicons.compose.uicons.thin.straight

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import com.uxicons.compose.uicons.Icons
import com.uxicons.compose.uicons.core.UXIcon

private var _WebDesign: ImageVector? = null

val Icons.Ts.WebDesign: ImageVector
    get() = _WebDesign ?: UXIcon(name = "WebDesign") {
            path(fill = SolidColor(Color.Black)) {
                moveToRelative(21.5f, 1f)
                lineTo(2.5f, 1f)
                curveTo(1.12f, 1f, 0f, 2.12f, 0f, 3.5f)
                verticalLineToRelative(19.5f)
                horizontalLineToRelative(24f)
                lineTo(24f, 3.5f)
                curveToRelative(0f, -1.38f, -1.12f, -2.5f, -2.5f, -2.5f)
                close()
                moveTo(2.5f, 2f)
                horizontalLineToRelative(19f)
                curveToRelative(0.83f, 0f, 1.5f, 0.67f, 1.5f, 1.5f)
                verticalLineToRelative(4.5f)
                lineTo(1f, 8f)
                lineTo(1f, 3.5f)
                curveToRelative(0f, -0.83f, 0.67f, -1.5f, 1.5f, -1.5f)
                close()
                moveTo(1f, 22f)
                verticalLineToRelative(-13f)
                horizontalLineToRelative(22f)
                verticalLineToRelative(13f)
                lineTo(1f, 22f)
                close()
                moveTo(3f, 5f)
                curveToRelative(0f, -0.55f, 0.45f, -1f, 1f, -1f)
                reflectiveCurveToRelative(1f, 0.45f, 1f, 1f)
                reflectiveCurveToRelative(-0.45f, 1f, -1f, 1f)
                reflectiveCurveToRelative(-1f, -0.45f, -1f, -1f)
                close()
                moveTo(6f, 5f)
                curveToRelative(0f, -0.55f, 0.45f, -1f, 1f, -1f)
                reflectiveCurveToRelative(1f, 0.45f, 1f, 1f)
                reflectiveCurveToRelative(-0.45f, 1f, -1f, 1f)
                reflectiveCurveToRelative(-1f, -0.45f, -1f, -1f)
                close()
                moveTo(9f, 5f)
                curveToRelative(0f, -0.55f, 0.45f, -1f, 1f, -1f)
                reflectiveCurveToRelative(1f, 0.45f, 1f, 1f)
                reflectiveCurveToRelative(-0.45f, 1f, -1f, 1f)
                reflectiveCurveToRelative(-1f, -0.45f, -1f, -1f)
                close()
                moveTo(15f, 20f)
                horizontalLineToRelative(6f)
                verticalLineToRelative(-9f)
                horizontalLineToRelative(-6f)
                verticalLineToRelative(9f)
                close()
                moveTo(16f, 12f)
                horizontalLineToRelative(4f)
                verticalLineToRelative(7f)
                horizontalLineToRelative(-4f)
                verticalLineToRelative(-7f)
                close()
                moveTo(3f, 15f)
                horizontalLineToRelative(11f)
                verticalLineToRelative(-4f)
                lineTo(3f, 11f)
                verticalLineToRelative(4f)
                close()
                moveTo(4f, 12f)
                horizontalLineToRelative(9f)
                verticalLineToRelative(2f)
                lineTo(4f, 14f)
                verticalLineToRelative(-2f)
                close()
                moveTo(3f, 20f)
                horizontalLineToRelative(11f)
                verticalLineToRelative(-4f)
                lineTo(3f, 16f)
                verticalLineToRelative(4f)
                close()
                moveTo(4f, 17f)
                horizontalLineToRelative(9f)
                verticalLineToRelative(2f)
                lineTo(4f, 19f)
                verticalLineToRelative(-2f)
                close()
            }
        }.also { _WebDesign = it}
