package com.uxicons.compose.uicons.regular.straight

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import com.uxicons.compose.uicons.Icons
import com.uxicons.compose.uicons.core.UXIcon

private var _CarBolt: ImageVector? = null

val Icons.Rs.CarBolt: ImageVector
    get() = _CarBolt ?: UXIcon(name = "CarBolt") {
            path(fill = SolidColor(Color.Black)) {
                moveTo(24f, 17.03f)
                curveToRelative(0f, -2.79f, -0.48f, -5.54f, -1.44f, -8.16f)
                lineToRelative(-2.14f, -5.89f)
                curveToRelative(-0.43f, -1.18f, -1.56f, -1.98f, -2.82f, -1.98f)
                lineTo(6.4f, 1.0f)
                curveToRelative(-1.26f, 0f, -2.39f, 0.79f, -2.82f, 1.98f)
                lineTo(1.44f, 8.87f)
                curveToRelative(-0.95f, 2.62f, -1.44f, 5.37f, -1.44f, 8.16f)
                verticalLineToRelative(1.97f)
                lineTo(2f, 19f)
                verticalLineToRelative(4f)
                horizontalLineToRelative(6f)
                verticalLineToRelative(-4f)
                horizontalLineToRelative(8f)
                verticalLineToRelative(4f)
                horizontalLineToRelative(6f)
                verticalLineToRelative(-4f)
                horizontalLineToRelative(2f)
                verticalLineToRelative(-1.97f)
                close()
                moveTo(6f, 21f)
                horizontalLineToRelative(-2f)
                verticalLineToRelative(-2f)
                horizontalLineToRelative(2f)
                verticalLineToRelative(2f)
                close()
                moveTo(20f, 21f)
                horizontalLineToRelative(-2f)
                verticalLineToRelative(-2f)
                horizontalLineToRelative(2f)
                verticalLineToRelative(2f)
                close()
                moveTo(2f, 17f)
                curveToRelative(0.0f, -1.35f, 0.13f, -2.69f, 0.37f, -4f)
                horizontalLineToRelative(1.63f)
                verticalLineToRelative(2f)
                horizontalLineToRelative(2f)
                verticalLineToRelative(-2f)
                horizontalLineToRelative(1f)
                verticalLineToRelative(-2f)
                lineTo(2.85f, 11f)
                curveToRelative(0.14f, -0.49f, 0.3f, -0.97f, 0.47f, -1.45f)
                lineTo(5.46f, 3.66f)
                curveToRelative(0.14f, -0.39f, 0.52f, -0.66f, 0.94f, -0.66f)
                horizontalLineToRelative(11.2f)
                curveToRelative(0.42f, 0f, 0.8f, 0.27f, 0.94f, 0.66f)
                lineToRelative(2.14f, 5.89f)
                curveToRelative(0.17f, 0.48f, 0.33f, 0.96f, 0.47f, 1.45f)
                horizontalLineToRelative(-4.15f)
                verticalLineToRelative(2f)
                horizontalLineToRelative(1f)
                verticalLineToRelative(2f)
                horizontalLineToRelative(2f)
                verticalLineToRelative(-2f)
                horizontalLineToRelative(1.63f)
                curveToRelative(0.25f, 1.31f, 0.37f, 2.65f, 0.37f, 4f)
                lineTo(2f, 17f)
                close()
                moveTo(14.81f, 9.85f)
                curveToRelative(0.27f, 0.5f, 0.25f, 1.1f, -0.04f, 1.58f)
                lineToRelative(-1.76f, 3.53f)
                lineToRelative(-1.79f, -0.89f)
                lineToRelative(1.53f, -3.07f)
                horizontalLineToRelative(-2.13f)
                curveToRelative(-0.51f, 0f, -0.99f, -0.24f, -1.3f, -0.65f)
                reflectiveCurveToRelative(-0.4f, -0.94f, -0.25f, -1.43f)
                lineToRelative(2.22f, -4.16f)
                lineToRelative(1.76f, 0.95f)
                lineToRelative(-1.78f, 3.29f)
                horizontalLineToRelative(2.12f)
                curveToRelative(0.59f, 0f, 1.13f, 0.32f, 1.41f, 0.85f)
                close()
            }
        }.also { _CarBolt = it}
