package com.uxicons.compose.uicons.regular.straight

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import com.uxicons.compose.uicons.Icons
import com.uxicons.compose.uicons.core.UXIcon

private var _DocumentPaid: ImageVector? = null

val Icons.Rs.DocumentPaid: ImageVector
    get() = _DocumentPaid ?: UXIcon(name = "DocumentPaid") {
            path(fill = SolidColor(Color.Black)) {
                moveToRelative(8.1f, 12f)
                horizontalLineToRelative(-2.1f)
                verticalLineToRelative(8f)
                horizontalLineToRelative(1.6f)
                verticalLineToRelative(-3f)
                horizontalLineToRelative(0.5f)
                curveToRelative(1.38f, 0f, 2.5f, -1.12f, 2.5f, -2.5f)
                reflectiveCurveToRelative(-1.12f, -2.5f, -2.5f, -2.5f)
                close()
                moveTo(8.1f, 15.4f)
                horizontalLineToRelative(-0.5f)
                verticalLineToRelative(-1.8f)
                horizontalLineToRelative(0.5f)
                curveToRelative(0.5f, 0f, 0.9f, 0.4f, 0.9f, 0.9f)
                reflectiveCurveToRelative(-0.4f, 0.9f, -0.9f, 0.9f)
                close()
                moveTo(16.8f, 12f)
                horizontalLineToRelative(1.6f)
                verticalLineToRelative(8f)
                horizontalLineToRelative(-1.6f)
                verticalLineToRelative(-8f)
                close()
                moveTo(12.24f, 18.53f)
                horizontalLineToRelative(2.01f)
                lineToRelative(0.26f, 1.47f)
                horizontalLineToRelative(1.49f)
                lineToRelative(-1.4f, -6.81f)
                curveToRelative(-0.12f, -0.67f, -0.59f, -1.19f, -1.35f, -1.19f)
                reflectiveCurveToRelative(-1.28f, 0.59f, -1.39f, 1.17f)
                lineToRelative(-1.37f, 6.83f)
                horizontalLineToRelative(1.47f)
                lineToRelative(0.28f, -1.47f)
                close()
                moveTo(13.24f, 13.71f)
                lineToRelative(0.64f, 3.29f)
                horizontalLineToRelative(-1.26f)
                lineToRelative(0.62f, -3.29f)
                close()
                moveTo(21.7f, 12f)
                horizontalLineToRelative(-2.3f)
                verticalLineToRelative(8f)
                horizontalLineToRelative(2.3f)
                curveToRelative(1.27f, 0f, 2.3f, -1.03f, 2.3f, -2.3f)
                verticalLineToRelative(-3.4f)
                curveToRelative(0f, -1.27f, -1.03f, -2.3f, -2.3f, -2.3f)
                close()
                moveTo(22.4f, 17.7f)
                curveToRelative(0f, 0.39f, -0.31f, 0.7f, -0.7f, 0.7f)
                reflectiveCurveToRelative(-0.7f, 0f, -0.7f, 0f)
                verticalLineToRelative(-4.8f)
                reflectiveCurveToRelative(0.31f, 0f, 0.7f, 0f)
                reflectiveCurveToRelative(0.7f, 0.31f, 0.7f, 0.7f)
                verticalLineToRelative(3.4f)
                close()
                moveTo(2f, 3f)
                curveToRelative(0f, -0.55f, 0.45f, -1f, 1f, -1f)
                horizontalLineToRelative(8f)
                verticalLineToRelative(7f)
                horizontalLineToRelative(7f)
                verticalLineToRelative(1f)
                horizontalLineToRelative(2f)
                verticalLineToRelative(-2.41f)
                lineTo(12.41f, 0f)
                lineTo(3f, 0f)
                curveTo(1.35f, 0f, 0f, 1.35f, 0f, 3f)
                verticalLineToRelative(21f)
                horizontalLineToRelative(20f)
                verticalLineToRelative(-2f)
                lineTo(2f, 22f)
                lineTo(2f, 3f)
                close()
                moveTo(13f, 3.41f)
                lineToRelative(3.59f, 3.59f)
                horizontalLineToRelative(-3.59f)
                verticalLineToRelative(-3.59f)
                close()
            }
        }.also { _DocumentPaid = it}
