package com.uxicons.compose.uicons.regular.straight

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import com.uxicons.compose.uicons.Icons
import com.uxicons.compose.uicons.core.UXIcon

private var _France: ImageVector? = null

val Icons.Rs.France: ImageVector
    get() = _France ?: UXIcon(name = "France") {
            path(fill = SolidColor(Color.Black)) {
                moveToRelative(24f, 4.5f)
                horizontalLineToRelative(-2.46f)
                lineToRelative(-1f, -1.5f)
                horizontalLineToRelative(-2.04f)
                lineToRelative(-1.5f, -2f)
                horizontalLineToRelative(-2f)
                verticalLineToRelative(-1f)
                horizontalLineToRelative(-2.33f)
                lineToRelative(-2.67f, 2f)
                verticalLineToRelative(1f)
                lineToRelative(-1.33f, 1f)
                horizontalLineToRelative(-0.97f)
                lineToRelative(-1.64f, -1.36f)
                lineToRelative(-1.72f, 2.37f)
                lineToRelative(-4.34f, 1.24f)
                verticalLineToRelative(2.17f)
                lineToRelative(1.98f, 0.66f)
                lineToRelative(2.27f, 2.1f)
                lineToRelative(1.97f, 2.62f)
                lineToRelative(-1.08f, 5.05f)
                lineToRelative(-1.15f, 1.19f)
                verticalLineToRelative(1.72f)
                lineToRelative(4.22f, 1.21f)
                lineToRelative(2.63f, 0.04f)
                lineToRelative(3.37f, 0.96f)
                lineToRelative(1.5f, 0.04f)
                lineToRelative(1f, -3f)
                horizontalLineToRelative(1.15f)
                lineToRelative(3.59f, 0.99f)
                lineToRelative(2.38f, -3.02f)
                lineToRelative(-1.83f, -1.87f)
                verticalLineToRelative(-0.71f)
                lineToRelative(1.01f, -1.12f)
                lineToRelative(-0.81f, -2.88f)
                lineToRelative(-0.78f, -0.14f)
                lineToRelative(0.54f, -1.24f)
                horizontalLineToRelative(2.01f)
                lineToRelative(-1.15f, -2.03f)
                lineToRelative(1.16f, -2.77f)
                verticalLineToRelative(-1.7f)
                close()
                moveTo(18.57f, 13.76f)
                lineTo(20.62f, 14.13f)
                lineTo(20.79f, 14.74f)
                lineTo(20f, 15.62f)
                verticalLineToRelative(2.29f)
                lineToRelative(1.17f, 1.2f)
                lineToRelative(-0.47f, 0.6f)
                lineToRelative(-2.44f, -0.71f)
                horizontalLineToRelative(-2.99f)
                lineToRelative(-0.97f, 2.91f)
                lineToRelative(-3.04f, -0.87f)
                lineToRelative(-2.63f, -0.04f)
                lineToRelative(-2.19f, -0.62f)
                lineToRelative(0.53f, -0.55f)
                lineToRelative(0.83f, -3.83f)
                horizontalLineToRelative(1.19f)
                verticalLineToRelative(-1.83f)
                lineToRelative(-3.2f, -4.27f)
                lineToRelative(-2.03f, -1.9f)
                horizontalLineToRelative(3.23f)
                verticalLineToRelative(-2f)
                horizontalLineToRelative(2.33f)
                lineToRelative(2.67f, -2f)
                verticalLineToRelative(-1f)
                lineToRelative(1f, -0.75f)
                verticalLineToRelative(0.75f)
                horizontalLineToRelative(3f)
                lineToRelative(1.5f, 2f)
                horizontalLineToRelative(1.97f)
                lineToRelative(1f, 1.5f)
                horizontalLineToRelative(1.24f)
                lineToRelative(-3.13f, 7.26f)
                close()
            }
        }.also { _France = it}
