package com.uxicons.compose.uicons.regular.straight

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import com.uxicons.compose.uicons.Icons
import com.uxicons.compose.uicons.core.UXIcon

private var _FreeDelivery: ImageVector? = null

val Icons.Rs.FreeDelivery: ImageVector
    get() = _FreeDelivery ?: UXIcon(name = "FreeDelivery") {
            path(fill = SolidColor(Color.Black)) {
                moveTo(24f, 12.65f)
                curveToRelative(0f, -0.54f, -0.09f, -1.07f, -0.26f, -1.58f)
                lineToRelative(-1.34f, -4.02f)
                curveToRelative(-0.41f, -1.23f, -1.55f, -2.05f, -2.85f, -2.05f)
                horizontalLineToRelative(-2.56f)
                verticalLineToRelative(-1f)
                curveToRelative(0f, -1.65f, -1.35f, -3f, -3f, -3f)
                lineTo(3f, 1.0f)
                curveTo(1.35f, 1f, 0f, 2.35f, 0f, 4f)
                verticalLineToRelative(1f)
                lineTo(2f, 5f)
                verticalLineToRelative(-1f)
                curveToRelative(0f, -0.55f, 0.45f, -1f, 1f, -1f)
                lineTo(14f, 3f)
                curveToRelative(0.55f, 0f, 1f, 0.45f, 1f, 1f)
                verticalLineToRelative(13f)
                lineTo(2f, 17f)
                verticalLineToRelative(-2f)
                lineTo(0f, 15f)
                verticalLineToRelative(4f)
                lineTo(2f, 19f)
                verticalLineToRelative(0.5f)
                curveToRelative(0f, 1.93f, 1.57f, 3.5f, 3.5f, 3.5f)
                reflectiveCurveToRelative(3.5f, -1.57f, 3.5f, -3.5f)
                verticalLineToRelative(-0.5f)
                horizontalLineToRelative(6f)
                verticalLineToRelative(0.5f)
                curveToRelative(0f, 1.93f, 1.57f, 3.5f, 3.5f, 3.5f)
                reflectiveCurveToRelative(3.5f, -1.57f, 3.5f, -3.5f)
                verticalLineToRelative(-0.5f)
                horizontalLineToRelative(2f)
                verticalLineToRelative(-6.35f)
                close()
                moveTo(19.56f, 7f)
                curveToRelative(0.43f, 0f, 0.81f, 0.27f, 0.95f, 0.68f)
                lineToRelative(1.1f, 3.32f)
                horizontalLineToRelative(-4.61f)
                lineTo(17f, 7f)
                horizontalLineToRelative(2.56f)
                close()
                moveTo(7f, 19.5f)
                curveToRelative(0f, 0.83f, -0.67f, 1.5f, -1.5f, 1.5f)
                reflectiveCurveToRelative(-1.5f, -0.67f, -1.5f, -1.5f)
                verticalLineToRelative(-0.5f)
                horizontalLineToRelative(3f)
                verticalLineToRelative(0.5f)
                close()
                moveTo(20f, 19.5f)
                curveToRelative(0f, 0.83f, -0.67f, 1.5f, -1.5f, 1.5f)
                reflectiveCurveToRelative(-1.5f, -0.67f, -1.5f, -1.5f)
                verticalLineToRelative(-0.5f)
                horizontalLineToRelative(3f)
                verticalLineToRelative(0.5f)
                close()
                moveTo(17f, 17f)
                verticalLineToRelative(-4f)
                horizontalLineToRelative(5f)
                verticalLineToRelative(4f)
                horizontalLineToRelative(-5f)
                close()
                moveTo(1.25f, 13f)
                lineTo(0f, 13f)
                lineTo(0f, 7f)
                lineTo(2.5f, 7f)
                verticalLineToRelative(1.25f)
                lineTo(1.25f, 8.25f)
                lineToRelative(0.01f, 1.25f)
                lineToRelative(1.24f, -0.0f)
                verticalLineToRelative(1.25f)
                lineToRelative(-1.25f, 0.0f)
                verticalLineToRelative(2.25f)
                close()
                moveTo(10.5f, 8.25f)
                horizontalLineToRelative(-1.25f)
                lineToRelative(0.01f, 1.18f)
                lineToRelative(1.24f, -0.0f)
                verticalLineToRelative(1.25f)
                lineToRelative(-1.24f, 0.0f)
                lineToRelative(-0.0f, 1.07f)
                horizontalLineToRelative(1.25f)
                verticalLineToRelative(1.25f)
                horizontalLineToRelative(-2.5f)
                lineTo(8f, 7f)
                horizontalLineToRelative(2.5f)
                verticalLineToRelative(1.25f)
                close()
                moveTo(14f, 8.25f)
                horizontalLineToRelative(-1.25f)
                lineToRelative(0.01f, 1.18f)
                lineToRelative(1.24f, -0.0f)
                verticalLineToRelative(1.25f)
                lineToRelative(-1.24f, 0.0f)
                lineToRelative(-0.0f, 1.07f)
                horizontalLineToRelative(1.25f)
                verticalLineToRelative(1.25f)
                horizontalLineToRelative(-2.5f)
                lineTo(11.5f, 7f)
                horizontalLineToRelative(2.5f)
                verticalLineToRelative(1.25f)
                close()
                moveTo(4.99f, 7f)
                horizontalLineToRelative(-1.49f)
                verticalLineToRelative(6f)
                horizontalLineToRelative(1.25f)
                verticalLineToRelative(-2.03f)
                lineToRelative(0.24f, -0.0f)
                curveToRelative(0.12f, 0f, 0.24f, -0.01f, 0.35f, -0.04f)
                lineToRelative(0.6f, 2.07f)
                horizontalLineToRelative(1.31f)
                lineToRelative(-0.81f, -2.65f)
                curveToRelative(0.34f, -0.36f, 0.56f, -0.83f, 0.56f, -1.36f)
                curveToRelative(0f, -1.09f, -0.9f, -1.99f, -2.01f, -1.99f)
                close()
                moveTo(4.99f, 9.72f)
                lineToRelative(-0.23f, 0.0f)
                lineToRelative(-0.01f, -1.47f)
                horizontalLineToRelative(0.24f)
                curveToRelative(0.41f, 0f, 0.76f, 0.34f, 0.76f, 0.73f)
                reflectiveCurveToRelative(-0.35f, 0.73f, -0.76f, 0.73f)
                close()
            }
        }.also { _FreeDelivery = it}
