package com.uxicons.compose.uicons.regular.straight

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import com.uxicons.compose.uicons.Icons
import com.uxicons.compose.uicons.core.UXIcon

private var _PasswordLock: ImageVector? = null

val Icons.Rs.PasswordLock: ImageVector
    get() = _PasswordLock ?: UXIcon(name = "PasswordLock") {
            path(fill = SolidColor(Color.Black)) {
                moveTo(19f, 20f)
                horizontalLineToRelative(-2f)
                verticalLineToRelative(-2f)
                horizontalLineToRelative(2f)
                verticalLineToRelative(2f)
                close()
                moveTo(22f, 14f)
                horizontalLineToRelative(2f)
                verticalLineToRelative(7f)
                curveToRelative(0f, 1.65f, -1.35f, 3f, -3f, 3f)
                horizontalLineToRelative(-6f)
                curveToRelative(-1.65f, 0f, -3f, -1.35f, -3f, -3f)
                verticalLineToRelative(-7f)
                horizontalLineToRelative(2f)
                verticalLineToRelative(-1f)
                curveToRelative(0f, -2.21f, 1.79f, -4f, 4f, -4f)
                reflectiveCurveToRelative(4f, 1.79f, 4f, 4f)
                verticalLineToRelative(1f)
                close()
                moveTo(16f, 14f)
                horizontalLineToRelative(4f)
                verticalLineToRelative(-1f)
                curveToRelative(0f, -1.1f, -0.9f, -2f, -2f, -2f)
                reflectiveCurveToRelative(-2f, 0.9f, -2f, 2f)
                verticalLineToRelative(1f)
                close()
                moveTo(22f, 16f)
                lineTo(14f, 16f)
                verticalLineToRelative(5f)
                curveToRelative(0f, 0.55f, 0.45f, 1f, 1f, 1f)
                horizontalLineToRelative(6f)
                curveToRelative(0.55f, 0f, 1f, -0.45f, 1f, -1f)
                verticalLineToRelative(-5f)
                close()
                moveTo(21f, 3f)
                lineTo(3f, 3f)
                curveToRelative(-1.65f, 0f, -3f, 1.35f, -3f, 3f)
                verticalLineToRelative(10f)
                lineTo(10f, 16f)
                verticalLineToRelative(-2f)
                lineTo(2f, 14f)
                lineTo(2f, 6f)
                curveToRelative(0f, -0.55f, 0.45f, -1f, 1f, -1f)
                lineTo(21f, 5f)
                curveToRelative(0.55f, 0f, 1f, 0.45f, 1f, 1f)
                verticalLineToRelative(2.54f)
                curveToRelative(0.99f, 0.89f, 1.68f, 2.1f, 1.91f, 3.46f)
                horizontalLineToRelative(0.09f)
                lineTo(24f, 6f)
                curveToRelative(0f, -1.65f, -1.35f, -3f, -3f, -3f)
                close()
                moveTo(7.54f, 7.04f)
                lineToRelative(-1.04f, 1.04f)
                lineToRelative(-1.04f, -1.04f)
                lineToRelative(-1.41f, 1.41f)
                lineToRelative(1.04f, 1.04f)
                lineToRelative(-1.04f, 1.04f)
                lineToRelative(1.41f, 1.41f)
                lineToRelative(1.04f, -1.04f)
                lineToRelative(1.04f, 1.04f)
                lineToRelative(1.41f, -1.41f)
                lineToRelative(-1.04f, -1.04f)
                lineToRelative(1.04f, -1.04f)
                lineToRelative(-1.41f, -1.41f)
                close()
                moveTo(10.99f, 11.96f)
                lineToRelative(3.5f, -3.5f)
                lineToRelative(-1.41f, -1.41f)
                lineToRelative(-1.04f, 1.04f)
                lineToRelative(-1.04f, -1.04f)
                lineToRelative(-1.41f, 1.41f)
                lineToRelative(1.04f, 1.04f)
                lineToRelative(-1.04f, 1.04f)
                lineToRelative(1.41f, 1.41f)
                close()
            }
        }.also { _PasswordLock = it}
