package com.uxicons.compose.uicons.regular.straight

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import com.uxicons.compose.uicons.Icons
import com.uxicons.compose.uicons.core.UXIcon

private var _PaymentQrcode: ImageVector? = null

val Icons.Rs.PaymentQrcode: ImageVector
    get() = _PaymentQrcode ?: UXIcon(name = "PaymentQrcode") {
            path(fill = SolidColor(Color.Black)) {
                moveToRelative(3f, 22f)
                horizontalLineToRelative(8f)
                verticalLineToRelative(2f)
                horizontalLineToRelative(-8f)
                curveToRelative(-1.65f, 0f, -3f, -1.35f, -3f, -3f)
                verticalLineToRelative(-21f)
                horizontalLineToRelative(16f)
                verticalLineToRelative(11f)
                horizontalLineToRelative(-2f)
                verticalLineToRelative(-9f)
                horizontalLineToRelative(-12f)
                verticalLineToRelative(19f)
                curveToRelative(0f, 0.55f, 0.45f, 1f, 1f, 1f)
                close()
                moveTo(6f, 18f)
                verticalLineToRelative(2f)
                horizontalLineToRelative(4f)
                verticalLineToRelative(-2f)
                close()
                moveTo(9.55f, 10.49f)
                lineTo(6.76f, 9.94f)
                curveToRelative(-0.27f, -0.05f, -0.46f, -0.29f, -0.46f, -0.56f)
                curveToRelative(0f, -0.32f, 0.26f, -0.57f, 0.57f, -0.57f)
                horizontalLineToRelative(2.13f)
                curveToRelative(0.32f, 0f, 0.58f, 0.21f, 0.67f, 0.5f)
                horizontalLineToRelative(1.62f)
                curveToRelative(-0.1f, -1.18f, -1.09f, -2.1f, -2.29f, -2.1f)
                horizontalLineToRelative(-0.2f)
                verticalLineToRelative(-1.2f)
                horizontalLineToRelative(-1.6f)
                verticalLineToRelative(1.2f)
                horizontalLineToRelative(-0.33f)
                curveToRelative(-1.2f, 0f, -2.17f, 0.97f, -2.17f, 2.17f)
                curveToRelative(0f, 1.03f, 0.73f, 1.93f, 1.75f, 2.13f)
                lineToRelative(2.79f, 0.56f)
                curveToRelative(0.27f, 0.05f, 0.46f, 0.29f, 0.46f, 0.56f)
                curveToRelative(0f, 0.32f, -0.26f, 0.57f, -0.57f, 0.57f)
                horizontalLineToRelative(-2.13f)
                curveToRelative(-0.32f, 0f, -0.58f, -0.21f, -0.67f, -0.5f)
                horizontalLineToRelative(-1.62f)
                curveToRelative(0.1f, 1.18f, 1.09f, 2.1f, 2.29f, 2.1f)
                horizontalLineToRelative(0.2f)
                verticalLineToRelative(1.2f)
                horizontalLineToRelative(1.6f)
                verticalLineToRelative(-1.2f)
                horizontalLineToRelative(0.33f)
                curveToRelative(1.2f, 0f, 2.17f, -0.97f, 2.17f, -2.17f)
                curveToRelative(0f, -1.03f, -0.73f, -1.93f, -1.75f, -2.13f)
                close()
                moveTo(19f, 24f)
                horizontalLineToRelative(2f)
                verticalLineToRelative(-2f)
                horizontalLineToRelative(-2f)
                close()
                moveTo(22f, 21f)
                horizontalLineToRelative(2f)
                verticalLineToRelative(-2f)
                horizontalLineToRelative(-2f)
                close()
                moveTo(19f, 21f)
                horizontalLineToRelative(2f)
                verticalLineToRelative(-2f)
                horizontalLineToRelative(-2f)
                close()
                moveTo(13f, 13f)
                horizontalLineToRelative(5f)
                verticalLineToRelative(5f)
                horizontalLineToRelative(-5f)
                close()
                moveTo(15f, 16f)
                horizontalLineToRelative(1f)
                verticalLineToRelative(-1f)
                horizontalLineToRelative(-1f)
                close()
                moveTo(13f, 19f)
                horizontalLineToRelative(5f)
                verticalLineToRelative(5f)
                horizontalLineToRelative(-5f)
                close()
                moveTo(15f, 22f)
                horizontalLineToRelative(1f)
                verticalLineToRelative(-1f)
                horizontalLineToRelative(-1f)
                close()
                moveTo(24f, 13f)
                verticalLineToRelative(5f)
                horizontalLineToRelative(-5f)
                verticalLineToRelative(-5f)
                close()
                moveTo(22f, 15f)
                horizontalLineToRelative(-1f)
                verticalLineToRelative(1f)
                horizontalLineToRelative(1f)
                close()
            }
        }.also { _PaymentQrcode = it}
