package com.uxicons.compose.uicons.regular.straight

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import com.uxicons.compose.uicons.Icons
import com.uxicons.compose.uicons.core.UXIcon

private var _Responsability: ImageVector? = null

val Icons.Rs.Responsability: ImageVector
    get() = _Responsability ?: UXIcon(name = "Responsability") {
            path(fill = SolidColor(Color.Black)) {
                moveToRelative(24f, 2.45f)
                verticalLineToRelative(2.55f)
                curveToRelative(0f, 1.1f, -0.9f, 2f, -2f, 2f)
                horizontalLineToRelative(-3f)
                curveToRelative(-1.1f, 0f, -2f, -0.9f, -2f, -2f)
                verticalLineToRelative(-3f)
                curveToRelative(0f, -1.1f, 0.9f, -2f, 2f, -2f)
                horizontalLineToRelative(3f)
                curveToRelative(0.46f, 0f, 0.87f, 0.16f, 1.21f, 0.41f)
                lineToRelative(-2.65f, 2.71f)
                lineToRelative(-1.11f, -1.2f)
                lineToRelative(-1.39f, 1.44f)
                lineToRelative(1.65f, 1.77f)
                curveToRelative(0.46f, 0.48f, 1.22f, 0.48f, 1.67f, 0.01f)
                lineToRelative(2.61f, -2.7f)
                close()
                moveTo(19.71f, 13.64f)
                lineToRelative(-1.65f, -1.77f)
                lineToRelative(1.39f, -1.44f)
                lineToRelative(1.11f, 1.2f)
                lineToRelative(2.65f, -2.71f)
                curveToRelative(-0.34f, -0.26f, -0.75f, -0.41f, -1.21f, -0.41f)
                horizontalLineToRelative(-3f)
                curveToRelative(-1.1f, 0f, -2f, 0.9f, -2f, 2f)
                verticalLineToRelative(3f)
                curveToRelative(0f, 1.1f, 0.9f, 2f, 2f, 2f)
                horizontalLineToRelative(3f)
                curveToRelative(1.1f, 0f, 2f, -0.9f, 2f, -2f)
                verticalLineToRelative(-2.55f)
                lineToRelative(-2.61f, 2.7f)
                curveToRelative(-0.46f, 0.47f, -1.22f, 0.47f, -1.67f, -0.01f)
                close()
                moveTo(19.71f, 22.14f)
                lineToRelative(-1.65f, -1.77f)
                lineToRelative(1.39f, -1.44f)
                lineToRelative(1.11f, 1.2f)
                lineToRelative(2.65f, -2.71f)
                curveToRelative(-0.34f, -0.26f, -0.75f, -0.41f, -1.21f, -0.41f)
                horizontalLineToRelative(-3f)
                curveToRelative(-1.1f, 0f, -2f, 0.9f, -2f, 2f)
                verticalLineToRelative(3f)
                curveToRelative(0f, 1.1f, 0.9f, 2f, 2f, 2f)
                horizontalLineToRelative(3f)
                curveToRelative(1.1f, 0f, 2f, -0.9f, 2f, -2f)
                verticalLineToRelative(-2.55f)
                lineToRelative(-2.61f, 2.7f)
                curveToRelative(-0.46f, 0.47f, -1.22f, 0.47f, -1.67f, -0.01f)
                close()
                moveTo(4.5f, 5f)
                curveToRelative(1.38f, 0f, 2.5f, -1.12f, 2.5f, -2.5f)
                reflectiveCurveTo(5.88f, 0f, 4.5f, 0f)
                reflectiveCurveToRelative(-2.5f, 1.12f, -2.5f, 2.5f)
                reflectiveCurveToRelative(1.12f, 2.5f, 2.5f, 2.5f)
                close()
                moveTo(9f, 9f)
                verticalLineToRelative(8f)
                horizontalLineToRelative(-2f)
                verticalLineToRelative(7f)
                horizontalLineToRelative(-2f)
                verticalLineToRelative(-7f)
                horizontalLineToRelative(-1f)
                verticalLineToRelative(7f)
                horizontalLineToRelative(-2f)
                verticalLineToRelative(-7f)
                lineTo(0f, 17f)
                verticalLineToRelative(-8f)
                curveToRelative(0f, -1.65f, 1.35f, -3f, 3f, -3f)
                horizontalLineToRelative(3f)
                curveToRelative(1.65f, 0f, 3f, 1.35f, 3f, 3f)
                close()
                moveTo(7f, 9f)
                curveToRelative(0f, -0.55f, -0.45f, -1f, -1f, -1f)
                horizontalLineToRelative(-3f)
                curveToRelative(-0.55f, 0f, -1f, 0.45f, -1f, 1f)
                verticalLineToRelative(6f)
                horizontalLineToRelative(5f)
                verticalLineToRelative(-6f)
                close()
                moveTo(11f, 4.5f)
                verticalLineToRelative(15f)
                curveToRelative(0f, 1.38f, 1.12f, 2.5f, 2.5f, 2.5f)
                horizontalLineToRelative(1.5f)
                verticalLineToRelative(-2f)
                horizontalLineToRelative(-1.5f)
                curveToRelative(-0.28f, 0f, -0.5f, -0.23f, -0.5f, -0.5f)
                verticalLineToRelative(-6.5f)
                horizontalLineToRelative(2f)
                verticalLineToRelative(-2f)
                horizontalLineToRelative(-2f)
                verticalLineToRelative(-6.5f)
                curveToRelative(0f, -0.28f, 0.22f, -0.5f, 0.5f, -0.5f)
                horizontalLineToRelative(1.5f)
                verticalLineToRelative(-2f)
                horizontalLineToRelative(-1.5f)
                curveToRelative(-1.38f, 0f, -2.5f, 1.12f, -2.5f, 2.5f)
                close()
            }
        }.also { _Responsability = it}
