package com.uxicons.compose.uicons.regular.straight

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import com.uxicons.compose.uicons.Icons
import com.uxicons.compose.uicons.core.UXIcon

private var _SmartphoneBusPayment: ImageVector? = null

val Icons.Rs.SmartphoneBusPayment: ImageVector
    get() = _SmartphoneBusPayment ?: UXIcon(name = "SmartphoneBusPayment") {
            path(fill = SolidColor(Color.Black)) {
                moveToRelative(6f, 19f)
                horizontalLineToRelative(3f)
                verticalLineToRelative(2f)
                horizontalLineToRelative(-3f)
                close()
                moveTo(24f, 19f)
                horizontalLineToRelative(-2f)
                verticalLineToRelative(1f)
                curveToRelative(0f, 1.65f, -1.35f, 3f, -3f, 3f)
                reflectiveCurveToRelative(-3f, -1.35f, -3f, -3f)
                verticalLineToRelative(-1f)
                horizontalLineToRelative(-1f)
                verticalLineToRelative(2f)
                curveToRelative(0f, 1.65f, -1.35f, 3f, -3f, 3f)
                horizontalLineToRelative(-9f)
                curveToRelative(-1.65f, 0f, -3f, -1.35f, -3f, -3f)
                verticalLineToRelative(-21f)
                horizontalLineToRelative(15f)
                verticalLineToRelative(2f)
                horizontalLineToRelative(2.7f)
                curveToRelative(1.18f, 0f, 2.26f, 0.7f, 2.74f, 1.78f)
                lineToRelative(3.13f, 7.04f)
                curveToRelative(0.28f, 0.64f, 0.43f, 1.32f, 0.43f, 2.03f)
                verticalLineToRelative(6.15f)
                close()
                moveTo(15f, 4f)
                verticalLineToRelative(6f)
                horizontalLineToRelative(6.02f)
                lineToRelative(-2.4f, -5.41f)
                curveToRelative(-0.16f, -0.36f, -0.52f, -0.59f, -0.91f, -0.59f)
                close()
                moveTo(2f, 2f)
                verticalLineToRelative(14f)
                horizontalLineToRelative(11f)
                verticalLineToRelative(-14f)
                close()
                moveTo(13f, 21f)
                verticalLineToRelative(-3f)
                horizontalLineToRelative(-11f)
                verticalLineToRelative(3f)
                curveToRelative(0f, 0.55f, 0.45f, 1f, 1f, 1f)
                horizontalLineToRelative(9f)
                curveToRelative(0.55f, 0f, 1f, -0.45f, 1f, -1f)
                close()
                moveTo(20f, 19f)
                horizontalLineToRelative(-2f)
                verticalLineToRelative(1f)
                curveToRelative(0f, 0.55f, 0.45f, 1f, 1f, 1f)
                reflectiveCurveToRelative(1f, -0.45f, 1f, -1f)
                close()
                moveTo(22f, 12.85f)
                curveToRelative(0f, -0.29f, -0.06f, -0.57f, -0.14f, -0.85f)
                horizontalLineToRelative(-6.86f)
                verticalLineToRelative(5f)
                horizontalLineToRelative(7f)
                close()
                moveTo(5.95f, 9.51f)
                lineTo(8.74f, 10.06f)
                curveToRelative(0.27f, 0.05f, 0.46f, 0.29f, 0.46f, 0.56f)
                curveToRelative(0f, 0.32f, -0.26f, 0.57f, -0.57f, 0.57f)
                horizontalLineToRelative(-2.13f)
                curveToRelative(-0.32f, 0f, -0.58f, -0.21f, -0.67f, -0.5f)
                horizontalLineToRelative(-1.62f)
                curveToRelative(0.1f, 1.18f, 1.09f, 2.1f, 2.29f, 2.1f)
                horizontalLineToRelative(0.2f)
                verticalLineToRelative(1.2f)
                horizontalLineToRelative(1.6f)
                verticalLineToRelative(-1.2f)
                horizontalLineToRelative(0.33f)
                curveToRelative(1.2f, 0f, 2.17f, -0.97f, 2.17f, -2.17f)
                curveToRelative(0f, -1.03f, -0.73f, -1.93f, -1.75f, -2.13f)
                lineToRelative(-2.79f, -0.56f)
                curveToRelative(-0.27f, -0.05f, -0.46f, -0.29f, -0.46f, -0.56f)
                curveToRelative(0f, -0.32f, 0.26f, -0.57f, 0.57f, -0.57f)
                horizontalLineToRelative(2.13f)
                curveToRelative(0.32f, 0f, 0.58f, 0.21f, 0.67f, 0.5f)
                horizontalLineToRelative(1.62f)
                curveToRelative(-0.1f, -1.18f, -1.09f, -2.1f, -2.29f, -2.1f)
                horizontalLineToRelative(-0.2f)
                verticalLineToRelative(-1.2f)
                horizontalLineToRelative(-1.6f)
                verticalLineToRelative(1.2f)
                horizontalLineToRelative(-0.33f)
                curveToRelative(-1.2f, 0f, -2.17f, 0.97f, -2.17f, 2.17f)
                curveToRelative(0f, 1.03f, 0.73f, 1.93f, 1.75f, 2.13f)
                close()
            }
        }.also { _SmartphoneBusPayment = it}
