package com.uxicons.compose.uicons.regular.straight

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import com.uxicons.compose.uicons.Icons
import com.uxicons.compose.uicons.core.UXIcon

private var _SolarPanelSun: ImageVector? = null

val Icons.Rs.SolarPanelSun: ImageVector
    get() = _SolarPanelSun ?: UXIcon(name = "SolarPanelSun") {
            path(fill = SolidColor(Color.Black)) {
                moveToRelative(13f, 20f)
                horizontalLineToRelative(11.12f)
                lineToRelative(-1.86f, -7.02f)
                curveToRelative(-0.46f, -1.75f, -2.05f, -2.98f, -3.87f, -2.98f)
                lineTo(5.61f, 10f)
                curveToRelative(-1.81f, 0f, -3.4f, 1.22f, -3.87f, 2.98f)
                lineTo(-0.12f, 20f)
                horizontalLineToRelative(11.12f)
                verticalLineToRelative(2f)
                horizontalLineToRelative(-5f)
                verticalLineToRelative(2f)
                horizontalLineToRelative(12f)
                verticalLineToRelative(-2f)
                horizontalLineToRelative(-5f)
                verticalLineToRelative(-2f)
                close()
                moveTo(14.18f, 14f)
                horizontalLineToRelative(-4.35f)
                lineToRelative(0.14f, -2f)
                horizontalLineToRelative(4.07f)
                lineToRelative(0.14f, 2f)
                close()
                moveTo(9.68f, 16f)
                horizontalLineToRelative(4.64f)
                lineToRelative(0.14f, 2f)
                horizontalLineToRelative(-4.92f)
                lineToRelative(0.14f, -2f)
                close()
                moveTo(16.59f, 18f)
                lineToRelative(-0.21f, -2f)
                horizontalLineToRelative(4.61f)
                lineToRelative(0.53f, 2f)
                horizontalLineToRelative(-4.93f)
                close()
                moveTo(20.46f, 14f)
                horizontalLineToRelative(-4.25f)
                lineToRelative(-0.17f, -2f)
                horizontalLineToRelative(3.12f)
                curveToRelative(0.45f, 0f, 0.85f, 0.3f, 0.97f, 0.74f)
                lineToRelative(0.33f, 1.26f)
                close()
                moveTo(7.96f, 12f)
                lineToRelative(-0.17f, 2f)
                lineTo(3.54f, 14f)
                lineToRelative(0.33f, -1.26f)
                curveToRelative(0.12f, -0.44f, 0.51f, -0.74f, 0.97f, -0.74f)
                horizontalLineToRelative(3.12f)
                close()
                moveTo(3.01f, 16f)
                horizontalLineToRelative(4.61f)
                lineToRelative(-0.26f, 2f)
                lineTo(2.48f, 18f)
                lineToRelative(0.53f, -2f)
                close()
                moveTo(9f, 8f)
                horizontalLineToRelative(-4.5f)
                verticalLineToRelative(-2f)
                horizontalLineToRelative(2.6f)
                curveToRelative(0.19f, -0.94f, 0.66f, -1.77f, 1.3f, -2.44f)
                lineToRelative(-1.65f, -2.38f)
                lineTo(8.4f, 0.04f)
                lineToRelative(1.64f, 2.37f)
                curveToRelative(0.6f, -0.26f, 1.26f, -0.42f, 1.96f, -0.42f)
                reflectiveCurveToRelative(1.35f, 0.16f, 1.96f, 0.42f)
                lineTo(15.62f, 0.02f)
                lineToRelative(1.65f, 1.14f)
                lineToRelative(-1.66f, 2.4f)
                curveToRelative(0.64f, 0.67f, 1.11f, 1.5f, 1.3f, 2.44f)
                horizontalLineToRelative(2.6f)
                verticalLineToRelative(2f)
                horizontalLineToRelative(-4.5f)
                verticalLineToRelative(-1f)
                curveToRelative(0f, -1.65f, -1.35f, -3f, -3f, -3f)
                reflectiveCurveToRelative(-3f, 1.35f, -3f, 3f)
                verticalLineToRelative(1f)
                close()
            }
        }.also { _SolarPanelSun = it}
