package com.uxicons.compose.uicons.bold.straight

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import com.uxicons.compose.uicons.Icons
import com.uxicons.compose.uicons.core.UXIcon

private var _FamilyDress: ImageVector? = null

val Icons.Bs.FamilyDress: ImageVector
    get() = _FamilyDress ?: UXIcon(name = "FamilyDress") {
            path(fill = SolidColor(Color.Black)) {
                moveToRelative(21f, 21f)
                verticalLineToRelative(3f)
                horizontalLineToRelative(-3f)
                verticalLineToRelative(-6f)
                horizontalLineToRelative(1.8f)
                lineToRelative(-1.07f, -8.56f)
                curveToRelative(-0.03f, -0.25f, -0.24f, -0.44f, -0.5f, -0.44f)
                horizontalLineToRelative(-1.99f)
                curveToRelative(0.17f, -0.47f, 0.26f, -0.97f, 0.26f, -1.5f)
                curveToRelative(0f, -0.51f, -0.1f, -0.99f, -0.26f, -1.45f)
                curveToRelative(0.17f, -0.03f, 0.35f, -0.05f, 0.53f, -0.05f)
                horizontalLineToRelative(1.47f)
                curveToRelative(1.76f, 0f, 3.25f, 1.32f, 3.47f, 3.07f)
                lineToRelative(1.49f, 11.93f)
                horizontalLineToRelative(-2.2f)
                close()
                moveTo(7.23f, 6f)
                horizontalLineToRelative(-1.47f)
                curveToRelative(-1.76f, 0f, -3.25f, 1.32f, -3.47f, 3.06f)
                lineToRelative(-1.49f, 11.94f)
                horizontalLineToRelative(2.2f)
                verticalLineToRelative(3f)
                horizontalLineToRelative(3f)
                verticalLineToRelative(-6f)
                horizontalLineToRelative(-1.8f)
                lineToRelative(1.07f, -8.56f)
                curveToRelative(0.03f, -0.25f, 0.24f, -0.44f, 0.5f, -0.44f)
                horizontalLineToRelative(1.99f)
                curveToRelative(-0.17f, -0.47f, -0.26f, -0.97f, -0.26f, -1.5f)
                curveToRelative(0f, -0.51f, 0.1f, -0.99f, 0.26f, -1.45f)
                curveToRelative(-0.17f, -0.03f, -0.35f, -0.05f, -0.53f, -0.05f)
                close()
                moveTo(17.5f, 5f)
                curveToRelative(1.38f, 0f, 2.5f, -1.12f, 2.5f, -2.5f)
                reflectiveCurveToRelative(-1.12f, -2.5f, -2.5f, -2.5f)
                reflectiveCurveToRelative(-2.5f, 1.12f, -2.5f, 2.5f)
                reflectiveCurveToRelative(1.12f, 2.5f, 2.5f, 2.5f)
                close()
                moveTo(6.5f, 5f)
                curveToRelative(1.38f, 0f, 2.5f, -1.12f, 2.5f, -2.5f)
                reflectiveCurveTo(7.88f, 0f, 6.5f, 0f)
                reflectiveCurveToRelative(-2.5f, 1.12f, -2.5f, 2.5f)
                reflectiveCurveToRelative(1.12f, 2.5f, 2.5f, 2.5f)
                close()
                moveTo(12f, 10f)
                curveToRelative(1.38f, 0f, 2.5f, -1.12f, 2.5f, -2.5f)
                reflectiveCurveToRelative(-1.12f, -2.5f, -2.5f, -2.5f)
                reflectiveCurveToRelative(-2.5f, 1.12f, -2.5f, 2.5f)
                reflectiveCurveToRelative(1.12f, 2.5f, 2.5f, 2.5f)
                close()
                moveTo(16f, 14.5f)
                verticalLineToRelative(5.5f)
                horizontalLineToRelative(-0.5f)
                verticalLineToRelative(4f)
                horizontalLineToRelative(-3f)
                verticalLineToRelative(-4f)
                horizontalLineToRelative(-1f)
                verticalLineToRelative(4f)
                horizontalLineToRelative(-3f)
                verticalLineToRelative(-4f)
                horizontalLineToRelative(-0.5f)
                verticalLineToRelative(-5.5f)
                curveToRelative(0f, -1.93f, 1.57f, -3.5f, 3.5f, -3.5f)
                horizontalLineToRelative(1f)
                curveToRelative(1.93f, 0f, 3.5f, 1.57f, 3.5f, 3.5f)
                close()
                moveTo(11f, 17f)
                horizontalLineToRelative(2f)
                verticalLineToRelative(-2.5f)
                curveToRelative(0f, -0.28f, -0.22f, -0.5f, -0.5f, -0.5f)
                horizontalLineToRelative(-1f)
                curveToRelative(-0.28f, 0f, -0.5f, 0.23f, -0.5f, 0.5f)
                verticalLineToRelative(2.5f)
                close()
            }
        }.also { _FamilyDress = it}
