package com.uxicons.compose.uicons.bold.straight

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import com.uxicons.compose.uicons.Icons
import com.uxicons.compose.uicons.core.UXIcon

private var _Fence: ImageVector? = null

val Icons.Bs.Fence: ImageVector
    get() = _Fence ?: UXIcon(name = "Fence") {
            path(fill = SolidColor(Color.Black)) {
                moveTo(24f, 11f)
                verticalLineToRelative(-3f)
                horizontalLineToRelative(-1f)
                verticalLineToRelative(-3.0f)
                lineTo(18f, 0.0f)
                lineToRelative(-5f, 5f)
                verticalLineToRelative(3.0f)
                horizontalLineToRelative(-2f)
                verticalLineToRelative(-3.0f)
                lineTo(6f, 0.0f)
                lineTo(1f, 5.0f)
                verticalLineToRelative(3.0f)
                lineTo(0f, 8f)
                verticalLineToRelative(3f)
                lineTo(1f, 11f)
                verticalLineToRelative(4f)
                lineTo(0f, 15f)
                verticalLineToRelative(3f)
                lineTo(1f, 18f)
                verticalLineToRelative(6f)
                lineTo(11f, 24f)
                verticalLineToRelative(-6f)
                horizontalLineToRelative(2f)
                verticalLineToRelative(6f)
                horizontalLineToRelative(10f)
                verticalLineToRelative(-6f)
                horizontalLineToRelative(1f)
                verticalLineToRelative(-3f)
                horizontalLineToRelative(-1f)
                verticalLineToRelative(-4f)
                horizontalLineToRelative(1f)
                close()
                moveTo(16f, 6.25f)
                lineToRelative(2f, -2f)
                lineToRelative(2f, 2f)
                verticalLineToRelative(1.75f)
                horizontalLineToRelative(-4f)
                verticalLineToRelative(-1.75f)
                close()
                moveTo(4f, 6.25f)
                lineToRelative(2f, -2f)
                lineToRelative(2f, 2f)
                verticalLineToRelative(1.75f)
                lineTo(4f, 8f)
                verticalLineToRelative(-1.75f)
                close()
                moveTo(4f, 11f)
                horizontalLineToRelative(4f)
                verticalLineToRelative(4f)
                lineTo(4f, 15f)
                verticalLineToRelative(-4f)
                close()
                moveTo(8f, 21f)
                lineTo(4f, 21f)
                verticalLineToRelative(-3f)
                horizontalLineToRelative(4f)
                verticalLineToRelative(3f)
                close()
                moveTo(11f, 15f)
                verticalLineToRelative(-4f)
                horizontalLineToRelative(2f)
                verticalLineToRelative(4f)
                horizontalLineToRelative(-2f)
                close()
                moveTo(20f, 21f)
                horizontalLineToRelative(-4f)
                verticalLineToRelative(-3f)
                horizontalLineToRelative(4f)
                verticalLineToRelative(3f)
                close()
                moveTo(20f, 15f)
                horizontalLineToRelative(-4f)
                verticalLineToRelative(-4f)
                horizontalLineToRelative(4f)
                verticalLineToRelative(4f)
                close()
            }
        }.also { _Fence = it}
