package com.uxicons.compose.uicons.bold.straight

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import com.uxicons.compose.uicons.Icons
import com.uxicons.compose.uicons.core.UXIcon

private var _GlobeUser: ImageVector? = null

val Icons.Bs.GlobeUser: ImageVector
    get() = _GlobeUser ?: UXIcon(name = "GlobeUser") {
            path(fill = SolidColor(Color.Black)) {
                moveTo(20f, 2f)
                curveToRelative(0f, -1.1f, 0.9f, -2f, 2f, -2f)
                reflectiveCurveToRelative(2f, 0.9f, 2f, 2f)
                reflectiveCurveToRelative(-0.9f, 2f, -2f, 2f)
                reflectiveCurveToRelative(-2f, -0.9f, -2f, -2f)
                close()
                moveTo(2f, 4f)
                curveToRelative(1.1f, 0f, 2f, -0.9f, 2f, -2f)
                reflectiveCurveTo(3.1f, 0f, 2f, 0f)
                reflectiveCurveTo(0f, 0.9f, 0f, 2f)
                reflectiveCurveToRelative(0.9f, 2f, 2f, 2f)
                close()
                moveTo(22f, 20f)
                curveToRelative(-1.1f, 0f, -2f, 0.9f, -2f, 2f)
                reflectiveCurveToRelative(0.9f, 2f, 2f, 2f)
                reflectiveCurveToRelative(2f, -0.9f, 2f, -2f)
                reflectiveCurveToRelative(-0.9f, -2f, -2f, -2f)
                close()
                moveTo(2f, 20f)
                curveToRelative(-1.1f, 0f, -2f, 0.9f, -2f, 2f)
                reflectiveCurveToRelative(0.9f, 2f, 2f, 2f)
                reflectiveCurveToRelative(2f, -0.9f, 2f, -2f)
                reflectiveCurveToRelative(-0.9f, -2f, -2f, -2f)
                close()
                moveTo(12f, 18f)
                curveToRelative(-3.31f, 0f, -6f, -2.69f, -6f, -6f)
                reflectiveCurveToRelative(2.69f, -6f, 6f, -6f)
                reflectiveCurveToRelative(6f, 2.69f, 6f, 6f)
                reflectiveCurveToRelative(-2.69f, 6f, -6f, 6f)
                close()
                moveTo(14.17f, 8.65f)
                curveToRelative(0.21f, 0.71f, 0.34f, 1.52f, 0.4f, 2.35f)
                horizontalLineToRelative(1.29f)
                curveToRelative(-0.25f, -0.98f, -0.86f, -1.81f, -1.68f, -2.35f)
                close()
                moveTo(12.97f, 13f)
                horizontalLineToRelative(-1.94f)
                curveToRelative(0.12f, 1.57f, 0.64f, 3f, 0.97f, 3f)
                reflectiveCurveToRelative(0.85f, -1.43f, 0.97f, -3f)
                close()
                moveTo(12.97f, 11f)
                curveToRelative(-0.12f, -1.57f, -0.69f, -3f, -0.97f, -3f)
                reflectiveCurveToRelative(-0.85f, 1.43f, -0.97f, 3f)
                horizontalLineToRelative(1.94f)
                close()
                moveTo(8.14f, 11f)
                horizontalLineToRelative(1.29f)
                curveToRelative(0.06f, -0.83f, 0.19f, -1.64f, 0.4f, -2.35f)
                curveToRelative(-0.82f, 0.54f, -1.43f, 1.37f, -1.68f, 2.35f)
                close()
                moveTo(9.83f, 15.35f)
                curveToRelative(-0.21f, -0.71f, -0.34f, -1.52f, -0.4f, -2.35f)
                horizontalLineToRelative(-1.29f)
                curveToRelative(0.25f, 0.98f, 0.86f, 1.81f, 1.68f, 2.35f)
                close()
                moveTo(15.86f, 13f)
                horizontalLineToRelative(-1.29f)
                curveToRelative(-0.06f, 0.83f, -0.19f, 1.64f, -0.4f, 2.35f)
                curveToRelative(0.82f, -0.54f, 1.43f, -1.37f, 1.68f, -2.35f)
                close()
                moveTo(18.0f, 3f)
                lineTo(18.0f, 0f)
                horizontalLineToRelative(-3f)
                lineTo(15.0f, 4.59f)
                curveToRelative(2.0f, 0.81f, 3.6f, 2.41f, 4.41f, 4.41f)
                horizontalLineToRelative(4.59f)
                verticalLineToRelative(-3f)
                horizontalLineToRelative(-3f)
                lineToRelative(-3f, -3f)
                close()
                moveTo(9.0f, 4.59f)
                lineTo(9.0f, 0f)
                horizontalLineToRelative(-3f)
                lineTo(6.0f, 3f)
                lineToRelative(-3f, 3f)
                lineTo(0f, 6f)
                verticalLineToRelative(3f)
                lineTo(4.59f, 9f)
                curveToRelative(0.81f, -2.0f, 2.41f, -3.6f, 4.41f, -4.41f)
                close()
                moveTo(4.59f, 15f)
                lineTo(0f, 15f)
                verticalLineToRelative(3f)
                lineTo(3f, 18f)
                lineToRelative(3f, 3f)
                verticalLineToRelative(3f)
                horizontalLineToRelative(3f)
                verticalLineToRelative(-4.59f)
                curveToRelative(-2.0f, -0.81f, -3.6f, -2.41f, -4.41f, -4.41f)
                close()
                moveTo(15f, 19.41f)
                verticalLineToRelative(4.59f)
                horizontalLineToRelative(3f)
                verticalLineToRelative(-3f)
                lineToRelative(3f, -3f)
                horizontalLineToRelative(3f)
                verticalLineToRelative(-3f)
                horizontalLineToRelative(-4.59f)
                curveToRelative(-0.81f, 2.0f, -2.41f, 3.6f, -4.41f, 4.41f)
                close()
            }
        }.also { _GlobeUser = it}
