package com.uxicons.compose.uicons.bold.straight

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import com.uxicons.compose.uicons.Icons
import com.uxicons.compose.uicons.core.UXIcon

private var _RentSignal: ImageVector? = null

val Icons.Bs.RentSignal: ImageVector
    get() = _RentSignal ?: UXIcon(name = "RentSignal") {
            path(fill = SolidColor(Color.Black)) {
                moveToRelative(9.5f, 2.5f)
                curveToRelative(0f, -1.38f, 1.12f, -2.5f, 2.5f, -2.5f)
                reflectiveCurveToRelative(2.5f, 1.12f, 2.5f, 2.5f)
                reflectiveCurveToRelative(-1.12f, 2.5f, -2.5f, 2.5f)
                reflectiveCurveToRelative(-2.5f, -1.12f, -2.5f, -2.5f)
                close()
                moveTo(4.5f, 14.6f)
                horizontalLineToRelative(-0.9f)
                verticalLineToRelative(1.8f)
                horizontalLineToRelative(0.9f)
                curveToRelative(0.5f, 0f, 0.9f, -0.4f, 0.9f, -0.9f)
                reflectiveCurveToRelative(-0.4f, -0.9f, -0.9f, -0.9f)
                close()
                moveTo(20.5f, 10f)
                horizontalLineToRelative(-0.03f)
                lineToRelative(-4.72f, -5.01f)
                curveToRelative(-0.57f, 0.85f, -1.42f, 1.5f, -2.41f, 1.81f)
                lineToRelative(3.01f, 3.2f)
                lineTo(7.65f, 10f)
                lineToRelative(3.01f, -3.2f)
                curveToRelative(-1.0f, -0.31f, -1.85f, -0.96f, -2.41f, -1.81f)
                lineToRelative(-4.72f, 5.01f)
                horizontalLineToRelative(-0.03f)
                curveToRelative(-1.93f, 0f, -3.5f, 1.57f, -3.5f, 3.5f)
                verticalLineToRelative(10.5f)
                horizontalLineToRelative(24f)
                verticalLineToRelative(-10.5f)
                curveToRelative(0f, -1.93f, -1.57f, -3.5f, -3.5f, -3.5f)
                close()
                moveTo(5.99f, 17.51f)
                curveToRelative(-0.02f, 0.01f, -0.02f, 0.01f, -0.04f, 0.03f)
                lineToRelative(1.05f, 3.46f)
                horizontalLineToRelative(-1.74f)
                lineToRelative(-0.87f, -3f)
                horizontalLineToRelative(-0.78f)
                verticalLineToRelative(3f)
                horizontalLineToRelative(-1.6f)
                verticalLineToRelative(-8f)
                horizontalLineToRelative(2.5f)
                curveToRelative(1.38f, 0f, 2.5f, 1.12f, 2.5f, 2.5f)
                curveToRelative(0f, 0.85f, -0.42f, 1.59f, -1.07f, 2.04f)
                curveToRelative(0.02f, -0.01f, 0.04f, -0.02f, 0.06f, -0.04f)
                close()
                moveTo(11f, 14.6f)
                horizontalLineToRelative(-1.4f)
                verticalLineToRelative(1.6f)
                horizontalLineToRelative(1.4f)
                verticalLineToRelative(1.6f)
                horizontalLineToRelative(-1.4f)
                verticalLineToRelative(1.6f)
                horizontalLineToRelative(1.4f)
                verticalLineToRelative(1.6f)
                horizontalLineToRelative(-3f)
                verticalLineToRelative(-8f)
                horizontalLineToRelative(3f)
                verticalLineToRelative(1.6f)
                close()
                moveTo(17f, 21f)
                horizontalLineToRelative(-1.6f)
                lineToRelative(-1.8f, -4.05f)
                verticalLineToRelative(4.05f)
                horizontalLineToRelative(-1.6f)
                verticalLineToRelative(-8f)
                horizontalLineToRelative(1.6f)
                verticalLineToRelative(0.01f)
                lineToRelative(1.8f, 4.05f)
                verticalLineToRelative(-4.06f)
                horizontalLineToRelative(1.6f)
                verticalLineToRelative(8f)
                close()
                moveTo(22f, 14.6f)
                horizontalLineToRelative(-1.2f)
                verticalLineToRelative(6.4f)
                horizontalLineToRelative(-1.6f)
                verticalLineToRelative(-6.4f)
                horizontalLineToRelative(-1.2f)
                verticalLineToRelative(-1.6f)
                horizontalLineToRelative(4f)
                verticalLineToRelative(1.6f)
                close()
            }
        }.also { _RentSignal = it}
